;;; This file was automatically generated by SWIG (http://www.swig.org).
;;; Version 3.0.2
;;;
;;; Do not make changes to this file unless you know what you are doing--modify
;;; the SWIG interface file instead.

(in-package :owlisp/llvm-ir)



;;;SWIG wrapper code starts here

(cl:defmacro defanonenum (cl:&body enums)
   "Converts anonymous enums to defconstants."
  `(cl:progn ,@(cl:loop for value in enums
                        for index = 0 then (cl:1+ index)
                        when (cl:listp value) do (cl:setf index (cl:second value)
                                                          value (cl:first value))
                        collect `(cl:defconstant ,value ,index))))

(cl:eval-when (:compile-toplevel :load-toplevel)
  (cl:unless (cl:fboundp 'swig-lispify)
    (cl:defun swig-lispify (name flag cl:&optional (package cl:*package*))
      (cl:labels ((helper (lst last rest cl:&aux (c (cl:car lst)))
                    (cl:cond
                      ((cl:null lst)
                       rest)
                      ((cl:upper-case-p c)
                       (helper (cl:cdr lst) 'upper
                               (cl:case last
                                 ((lower digit) (cl:list* c #\- rest))
                                 (cl:t (cl:cons c rest)))))
                      ((cl:lower-case-p c)
                       (helper (cl:cdr lst) 'lower (cl:cons (cl:char-upcase c) rest)))
                      ((cl:digit-char-p c)
                       (helper (cl:cdr lst) 'digit 
                               (cl:case last
                                 ((upper lower) (cl:list* c #\- rest))
                                 (cl:t (cl:cons c rest)))))
                      ((cl:char-equal c #\_)
                       (helper (cl:cdr lst) '_ (cl:cons #\- rest)))
                      (cl:t
                       (cl:error "Invalid character: ~A" c)))))
        (cl:let ((fix (cl:case flag
                        ((constant enumvalue) "+")
                        (variable "*")
                        (cl:t ""))))
          (cl:intern
           (cl:concatenate
            'cl:string
            fix
            (cl:nreverse (helper (cl:concatenate 'cl:list name) cl:nil cl:nil))
            fix)
           package))))))

;;;SWIG wrapper code ends here


(cffi:defcenum LLVMAttribute
	(:LLVMZExtAttribute #.(cl:ash 1 0))
	(:LLVMSExtAttribute #.(cl:ash 1 1))
	(:LLVMNoReturnAttribute #.(cl:ash 1 2))
	(:LLVMInRegAttribute #.(cl:ash 1 3))
	(:LLVMStructRetAttribute #.(cl:ash 1 4))
	(:LLVMNoUnwindAttribute #.(cl:ash 1 5))
	(:LLVMNoAliasAttribute #.(cl:ash 1 6))
	(:LLVMByValAttribute #.(cl:ash 1 7))
	(:LLVMNestAttribute #.(cl:ash 1 8))
	(:LLVMReadNoneAttribute #.(cl:ash 1 9))
	(:LLVMReadOnlyAttribute #.(cl:ash 1 10))
	(:LLVMNoInlineAttribute #.(cl:ash 1 11))
	(:LLVMAlwaysInlineAttribute #.(cl:ash 1 12))
	(:LLVMOptimizeForSizeAttribute #.(cl:ash 1 13))
	(:LLVMStackProtectAttribute #.(cl:ash 1 14))
	(:LLVMStackProtectReqAttribute #.(cl:ash 1 15))
	(:LLVMAlignment #.(cl:ash 31 16))
	(:LLVMNoCaptureAttribute #.(cl:ash 1 21))
	(:LLVMNoRedZoneAttribute #.(cl:ash 1 22))
	(:LLVMNoImplicitFloatAttribute #.(cl:ash 1 23))
	(:LLVMNakedAttribute #.(cl:ash 1 24))
	(:LLVMInlineHintAttribute #.(cl:ash 1 25))
	(:LLVMStackAlignment #.(cl:ash 7 26))
	(:LLVMReturnsTwice #.(cl:ash 1 29))
	(:LLVMUWTable #.(cl:ash 1 30))
	(:LLVMNonLazyBind #.(cl:ash 1 31)))

(cl:export 'LLVMAttribute)

(cffi:defcenum LLVMOpcode
	(:LLVMRet #.1)
	(:LLVMBr #.2)
	(:LLVMSwitch #.3)
	(:LLVMIndirectBr #.4)
	(:LLVMInvoke #.5)
	(:LLVMUnreachable #.7)
	(:LLVMAdd #.8)
	(:LLVMFAdd #.9)
	(:LLVMSub #.10)
	(:LLVMFSub #.11)
	(:LLVMMul #.12)
	(:LLVMFMul #.13)
	(:LLVMUDiv #.14)
	(:LLVMSDiv #.15)
	(:LLVMFDiv #.16)
	(:LLVMURem #.17)
	(:LLVMSRem #.18)
	(:LLVMFRem #.19)
	(:LLVMShl #.20)
	(:LLVMLShr #.21)
	(:LLVMAShr #.22)
	(:LLVMAnd #.23)
	(:LLVMOr #.24)
	(:LLVMXor #.25)
	(:LLVMAlloca #.26)
	(:LLVMLoad #.27)
	(:LLVMStore #.28)
	(:LLVMGetElementPtr #.29)
	(:LLVMTrunc #.30)
	(:LLVMZExt #.31)
	(:LLVMSExt #.32)
	(:LLVMFPToUI #.33)
	(:LLVMFPToSI #.34)
	(:LLVMUIToFP #.35)
	(:LLVMSIToFP #.36)
	(:LLVMFPTrunc #.37)
	(:LLVMFPExt #.38)
	(:LLVMPtrToInt #.39)
	(:LLVMIntToPtr #.40)
	(:LLVMBitCast #.41)
	(:LLVMAddrSpaceCast #.60)
	(:LLVMICmp #.42)
	(:LLVMFCmp #.43)
	(:LLVMPHI #.44)
	(:LLVMCall #.45)
	(:LLVMSelect #.46)
	(:LLVMUserOp1 #.47)
	(:LLVMUserOp2 #.48)
	(:LLVMVAArg #.49)
	(:LLVMExtractElement #.50)
	(:LLVMInsertElement #.51)
	(:LLVMShuffleVector #.52)
	(:LLVMExtractValue #.53)
	(:LLVMInsertValue #.54)
	(:LLVMFence #.55)
	(:LLVMAtomicCmpXchg #.56)
	(:LLVMAtomicRMW #.57)
	(:LLVMResume #.58)
	(:LLVMLandingPad #.59))

(cl:export 'LLVMOpcode)

(cffi:defcenum LLVMTypeKind
	:LLVMVoidTypeKind
	:LLVMHalfTypeKind
	:LLVMFloatTypeKind
	:LLVMDoubleTypeKind
	:LLVMX86_FP80TypeKind
	:LLVMFP128TypeKind
	:LLVMPPC_FP128TypeKind
	:LLVMLabelTypeKind
	:LLVMIntegerTypeKind
	:LLVMFunctionTypeKind
	:LLVMStructTypeKind
	:LLVMArrayTypeKind
	:LLVMPointerTypeKind
	:LLVMVectorTypeKind
	:LLVMMetadataTypeKind
	:LLVMX86_MMXTypeKind)

(cl:export 'LLVMTypeKind)

(cffi:defcenum LLVMLinkage
	:LLVMExternalLinkage
	:LLVMAvailableExternallyLinkage
	:LLVMLinkOnceAnyLinkage
	:LLVMLinkOnceODRLinkage
	:LLVMLinkOnceODRAutoHideLinkage
	:LLVMWeakAnyLinkage
	:LLVMWeakODRLinkage
	:LLVMAppendingLinkage
	:LLVMInternalLinkage
	:LLVMPrivateLinkage
	:LLVMDLLImportLinkage
	:LLVMDLLExportLinkage
	:LLVMExternalWeakLinkage
	:LLVMGhostLinkage
	:LLVMCommonLinkage
	:LLVMLinkerPrivateLinkage
	:LLVMLinkerPrivateWeakLinkage)

(cl:export 'LLVMLinkage)

(cffi:defcenum LLVMVisibility
	:LLVMDefaultVisibility
	:LLVMHiddenVisibility
	:LLVMProtectedVisibility)

(cl:export 'LLVMVisibility)

(cffi:defcenum LLVMCallConv
	(:LLVMCCallConv #.0)
	(:LLVMFastCallConv #.8)
	(:LLVMColdCallConv #.9)
	(:LLVMWebKitJSCallConv #.12)
	(:LLVMAnyRegCallConv #.13)
	(:LLVMX86StdcallCallConv #.64)
	(:LLVMX86FastcallCallConv #.65))

(cl:export 'LLVMCallConv)

(cffi:defcenum LLVMIntPredicate
	(:LLVMIntEQ #.32)
	:LLVMIntNE
	:LLVMIntUGT
	:LLVMIntUGE
	:LLVMIntULT
	:LLVMIntULE
	:LLVMIntSGT
	:LLVMIntSGE
	:LLVMIntSLT
	:LLVMIntSLE)

(cl:export 'LLVMIntPredicate)

(cffi:defcenum LLVMRealPredicate
	:LLVMRealPredicateFalse
	:LLVMRealOEQ
	:LLVMRealOGT
	:LLVMRealOGE
	:LLVMRealOLT
	:LLVMRealOLE
	:LLVMRealONE
	:LLVMRealORD
	:LLVMRealUNO
	:LLVMRealUEQ
	:LLVMRealUGT
	:LLVMRealUGE
	:LLVMRealULT
	:LLVMRealULE
	:LLVMRealUNE
	:LLVMRealPredicateTrue)

(cl:export 'LLVMRealPredicate)

(cffi:defcenum LLVMLandingPadClauseTy
	:LLVMLandingPadCatch
	:LLVMLandingPadFilter)

(cl:export 'LLVMLandingPadClauseTy)

(cffi:defcenum LLVMThreadLocalMode
	(:LLVMNotThreadLocal #.0)
	:LLVMGeneralDynamicTLSModel
	:LLVMLocalDynamicTLSModel
	:LLVMInitialExecTLSModel
	:LLVMLocalExecTLSModel)

(cl:export 'LLVMThreadLocalMode)

(cffi:defcenum LLVMAtomicOrdering
	(:LLVMAtomicOrderingNotAtomic #.0)
	(:LLVMAtomicOrderingUnordered #.1)
	(:LLVMAtomicOrderingMonotonic #.2)
	(:LLVMAtomicOrderingAcquire #.4)
	(:LLVMAtomicOrderingRelease #.5)
	(:LLVMAtomicOrderingAcquireRelease #.6)
	(:LLVMAtomicOrderingSequentiallyConsistent #.7))

(cl:export 'LLVMAtomicOrdering)

(cffi:defcenum LLVMAtomicRMWBinOp
	:LLVMAtomicRMWBinOpXchg
	:LLVMAtomicRMWBinOpAdd
	:LLVMAtomicRMWBinOpSub
	:LLVMAtomicRMWBinOpAnd
	:LLVMAtomicRMWBinOpNand
	:LLVMAtomicRMWBinOpOr
	:LLVMAtomicRMWBinOpXor
	:LLVMAtomicRMWBinOpMax
	:LLVMAtomicRMWBinOpMin
	:LLVMAtomicRMWBinOpUMax
	:LLVMAtomicRMWBinOpUMin)

(cl:export 'LLVMAtomicRMWBinOp)

(cffi:defcfun ("LLVMInitializeCore" LLVMInitializeCore) :void
  (R :pointer))

(cl:export 'LLVMInitializeCore)

(cffi:defcfun ("LLVMShutdown" LLVMShutdown) :void)

(cl:export 'LLVMShutdown)

(cffi:defcfun ("LLVMCreateMessage" LLVMCreateMessage) :string
  (Message :string))

(cl:export 'LLVMCreateMessage)

(cffi:defcfun ("LLVMDisposeMessage" LLVMDisposeMessage) :void
  (Message :string))

(cl:export 'LLVMDisposeMessage)

(cffi:defcfun ("LLVMInstallFatalErrorHandler" LLVMInstallFatalErrorHandler) :void
  (Handler :pointer))

(cl:export 'LLVMInstallFatalErrorHandler)

(cffi:defcfun ("LLVMResetFatalErrorHandler" LLVMResetFatalErrorHandler) :void)

(cl:export 'LLVMResetFatalErrorHandler)

(cffi:defcfun ("LLVMEnablePrettyStackTrace" LLVMEnablePrettyStackTrace) :void)

(cl:export 'LLVMEnablePrettyStackTrace)

(cffi:defcfun ("LLVMContextCreate" LLVMContextCreate) :pointer)

(cl:export 'LLVMContextCreate)

(cffi:defcfun ("LLVMGetGlobalContext" LLVMGetGlobalContext) :pointer)

(cl:export 'LLVMGetGlobalContext)

(cffi:defcfun ("LLVMContextDispose" LLVMContextDispose) :void
  (C :pointer))

(cl:export 'LLVMContextDispose)

(cffi:defcfun ("LLVMGetMDKindIDInContext" LLVMGetMDKindIDInContext) :unsigned-int
  (C :pointer)
  (Name :string)
  (SLen :unsigned-int))

(cl:export 'LLVMGetMDKindIDInContext)

(cffi:defcfun ("LLVMGetMDKindID" LLVMGetMDKindID) :unsigned-int
  (Name :string)
  (SLen :unsigned-int))

(cl:export 'LLVMGetMDKindID)

(cffi:defcfun ("LLVMModuleCreateWithName" LLVMModuleCreateWithName) :pointer
  (ModuleID :string))

(cl:export 'LLVMModuleCreateWithName)

(cffi:defcfun ("LLVMModuleCreateWithNameInContext" LLVMModuleCreateWithNameInContext) :pointer
  (ModuleID :string)
  (C :pointer))

(cl:export 'LLVMModuleCreateWithNameInContext)

(cffi:defcfun ("LLVMDisposeModule" LLVMDisposeModule) :void
  (M :pointer))

(cl:export 'LLVMDisposeModule)

(cffi:defcfun ("LLVMGetDataLayout" LLVMGetDataLayout) :string
  (M :pointer))

(cl:export 'LLVMGetDataLayout)

(cffi:defcfun ("LLVMSetDataLayout" LLVMSetDataLayout) :void
  (M :pointer)
  (Triple :string))

(cl:export 'LLVMSetDataLayout)

(cffi:defcfun ("LLVMGetTarget" LLVMGetTarget) :string
  (M :pointer))

(cl:export 'LLVMGetTarget)

(cffi:defcfun ("LLVMSetTarget" LLVMSetTarget) :void
  (M :pointer)
  (Triple :string))

(cl:export 'LLVMSetTarget)

(cffi:defcfun ("LLVMDumpModule" LLVMDumpModule) :void
  (M :pointer))

(cl:export 'LLVMDumpModule)

(cffi:defcfun ("LLVMPrintModuleToFile" LLVMPrintModuleToFile) :int
  (M :pointer)
  (Filename :string)
  (ErrorMessage :pointer))

(cl:export 'LLVMPrintModuleToFile)

(cffi:defcfun ("LLVMPrintModuleToString" LLVMPrintModuleToString) :string
  (M :pointer))

(cl:export 'LLVMPrintModuleToString)

(cffi:defcfun ("LLVMSetModuleInlineAsm" LLVMSetModuleInlineAsm) :void
  (M :pointer)
  (Asm :string))

(cl:export 'LLVMSetModuleInlineAsm)

(cffi:defcfun ("LLVMGetModuleContext" LLVMGetModuleContext) :pointer
  (M :pointer))

(cl:export 'LLVMGetModuleContext)

(cffi:defcfun ("LLVMGetTypeByName" LLVMGetTypeByName) :pointer
  (M :pointer)
  (Name :string))

(cl:export 'LLVMGetTypeByName)

(cffi:defcfun ("LLVMGetNamedMetadataNumOperands" LLVMGetNamedMetadataNumOperands) :unsigned-int
  (M :pointer)
  (name :string))

(cl:export 'LLVMGetNamedMetadataNumOperands)

(cffi:defcfun ("LLVMGetNamedMetadataOperands" LLVMGetNamedMetadataOperands) :void
  (M :pointer)
  (name :string)
  (Dest :pointer))

(cl:export 'LLVMGetNamedMetadataOperands)

(cffi:defcfun ("LLVMAddNamedMetadataOperand" LLVMAddNamedMetadataOperand) :void
  (M :pointer)
  (name :string)
  (Val :pointer))

(cl:export 'LLVMAddNamedMetadataOperand)

(cffi:defcfun ("LLVMAddFunction" LLVMAddFunction) :pointer
  (M :pointer)
  (Name :string)
  (FunctionTy :pointer))

(cl:export 'LLVMAddFunction)

(cffi:defcfun ("LLVMGetNamedFunction" LLVMGetNamedFunction) :pointer
  (M :pointer)
  (Name :string))

(cl:export 'LLVMGetNamedFunction)

(cffi:defcfun ("LLVMGetFirstFunction" LLVMGetFirstFunction) :pointer
  (M :pointer))

(cl:export 'LLVMGetFirstFunction)

(cffi:defcfun ("LLVMGetLastFunction" LLVMGetLastFunction) :pointer
  (M :pointer))

(cl:export 'LLVMGetLastFunction)

(cffi:defcfun ("LLVMGetNextFunction" LLVMGetNextFunction) :pointer
  (Fn :pointer))

(cl:export 'LLVMGetNextFunction)

(cffi:defcfun ("LLVMGetPreviousFunction" LLVMGetPreviousFunction) :pointer
  (Fn :pointer))

(cl:export 'LLVMGetPreviousFunction)

(cffi:defcfun ("LLVMGetTypeKind" LLVMGetTypeKind) LLVMTypeKind
  (Ty :pointer))

(cl:export 'LLVMGetTypeKind)

(cffi:defcfun ("LLVMTypeIsSized" LLVMTypeIsSized) :int
  (Ty :pointer))

(cl:export 'LLVMTypeIsSized)

(cffi:defcfun ("LLVMGetTypeContext" LLVMGetTypeContext) :pointer
  (Ty :pointer))

(cl:export 'LLVMGetTypeContext)

(cffi:defcfun ("LLVMDumpType" LLVMDumpType) :void
  (Val :pointer))

(cl:export 'LLVMDumpType)

(cffi:defcfun ("LLVMPrintTypeToString" LLVMPrintTypeToString) :string
  (Val :pointer))

(cl:export 'LLVMPrintTypeToString)

(cffi:defcfun ("LLVMInt1TypeInContext" LLVMInt1TypeInContext) :pointer
  (C :pointer))

(cl:export 'LLVMInt1TypeInContext)

(cffi:defcfun ("LLVMInt8TypeInContext" LLVMInt8TypeInContext) :pointer
  (C :pointer))

(cl:export 'LLVMInt8TypeInContext)

(cffi:defcfun ("LLVMInt16TypeInContext" LLVMInt16TypeInContext) :pointer
  (C :pointer))

(cl:export 'LLVMInt16TypeInContext)

(cffi:defcfun ("LLVMInt32TypeInContext" LLVMInt32TypeInContext) :pointer
  (C :pointer))

(cl:export 'LLVMInt32TypeInContext)

(cffi:defcfun ("LLVMInt64TypeInContext" LLVMInt64TypeInContext) :pointer
  (C :pointer))

(cl:export 'LLVMInt64TypeInContext)

(cffi:defcfun ("LLVMIntTypeInContext" LLVMIntTypeInContext) :pointer
  (C :pointer)
  (NumBits :unsigned-int))

(cl:export 'LLVMIntTypeInContext)

(cffi:defcfun ("LLVMInt1Type" LLVMInt1Type) :pointer)

(cl:export 'LLVMInt1Type)

(cffi:defcfun ("LLVMInt8Type" LLVMInt8Type) :pointer)

(cl:export 'LLVMInt8Type)

(cffi:defcfun ("LLVMInt16Type" LLVMInt16Type) :pointer)

(cl:export 'LLVMInt16Type)

(cffi:defcfun ("LLVMInt32Type" LLVMInt32Type) :pointer)

(cl:export 'LLVMInt32Type)

(cffi:defcfun ("LLVMInt64Type" LLVMInt64Type) :pointer)

(cl:export 'LLVMInt64Type)

(cffi:defcfun ("LLVMIntType" LLVMIntType) :pointer
  (NumBits :unsigned-int))

(cl:export 'LLVMIntType)

(cffi:defcfun ("LLVMGetIntTypeWidth" LLVMGetIntTypeWidth) :unsigned-int
  (IntegerTy :pointer))

(cl:export 'LLVMGetIntTypeWidth)

(cffi:defcfun ("LLVMHalfTypeInContext" LLVMHalfTypeInContext) :pointer
  (C :pointer))

(cl:export 'LLVMHalfTypeInContext)

(cffi:defcfun ("LLVMFloatTypeInContext" LLVMFloatTypeInContext) :pointer
  (C :pointer))

(cl:export 'LLVMFloatTypeInContext)

(cffi:defcfun ("LLVMDoubleTypeInContext" LLVMDoubleTypeInContext) :pointer
  (C :pointer))

(cl:export 'LLVMDoubleTypeInContext)

(cffi:defcfun ("LLVMX86FP80TypeInContext" LLVMX86FP80TypeInContext) :pointer
  (C :pointer))

(cl:export 'LLVMX86FP80TypeInContext)

(cffi:defcfun ("LLVMFP128TypeInContext" LLVMFP128TypeInContext) :pointer
  (C :pointer))

(cl:export 'LLVMFP128TypeInContext)

(cffi:defcfun ("LLVMPPCFP128TypeInContext" LLVMPPCFP128TypeInContext) :pointer
  (C :pointer))

(cl:export 'LLVMPPCFP128TypeInContext)

(cffi:defcfun ("LLVMHalfType" LLVMHalfType) :pointer)

(cl:export 'LLVMHalfType)

(cffi:defcfun ("LLVMFloatType" LLVMFloatType) :pointer)

(cl:export 'LLVMFloatType)

(cffi:defcfun ("LLVMDoubleType" LLVMDoubleType) :pointer)

(cl:export 'LLVMDoubleType)

(cffi:defcfun ("LLVMX86FP80Type" LLVMX86FP80Type) :pointer)

(cl:export 'LLVMX86FP80Type)

(cffi:defcfun ("LLVMFP128Type" LLVMFP128Type) :pointer)

(cl:export 'LLVMFP128Type)

(cffi:defcfun ("LLVMPPCFP128Type" LLVMPPCFP128Type) :pointer)

(cl:export 'LLVMPPCFP128Type)

(cffi:defcfun ("LLVMFunctionType" LLVMFunctionType) :pointer
  (ReturnType :pointer)
  (ParamTypes :pointer)
  (ParamCount :unsigned-int)
  (IsVarArg :int))

(cl:export 'LLVMFunctionType)

(cffi:defcfun ("LLVMIsFunctionVarArg" LLVMIsFunctionVarArg) :int
  (FunctionTy :pointer))

(cl:export 'LLVMIsFunctionVarArg)

(cffi:defcfun ("LLVMGetReturnType" LLVMGetReturnType) :pointer
  (FunctionTy :pointer))

(cl:export 'LLVMGetReturnType)

(cffi:defcfun ("LLVMCountParamTypes" LLVMCountParamTypes) :unsigned-int
  (FunctionTy :pointer))

(cl:export 'LLVMCountParamTypes)

(cffi:defcfun ("LLVMGetParamTypes" LLVMGetParamTypes) :void
  (FunctionTy :pointer)
  (Dest :pointer))

(cl:export 'LLVMGetParamTypes)

(cffi:defcfun ("LLVMStructTypeInContext" LLVMStructTypeInContext) :pointer
  (C :pointer)
  (ElementTypes :pointer)
  (ElementCount :unsigned-int)
  (Packed :int))

(cl:export 'LLVMStructTypeInContext)

(cffi:defcfun ("LLVMStructType" LLVMStructType) :pointer
  (ElementTypes :pointer)
  (ElementCount :unsigned-int)
  (Packed :int))

(cl:export 'LLVMStructType)

(cffi:defcfun ("LLVMStructCreateNamed" LLVMStructCreateNamed) :pointer
  (C :pointer)
  (Name :string))

(cl:export 'LLVMStructCreateNamed)

(cffi:defcfun ("LLVMGetStructName" LLVMGetStructName) :string
  (Ty :pointer))

(cl:export 'LLVMGetStructName)

(cffi:defcfun ("LLVMStructSetBody" LLVMStructSetBody) :void
  (StructTy :pointer)
  (ElementTypes :pointer)
  (ElementCount :unsigned-int)
  (Packed :int))

(cl:export 'LLVMStructSetBody)

(cffi:defcfun ("LLVMCountStructElementTypes" LLVMCountStructElementTypes) :unsigned-int
  (StructTy :pointer))

(cl:export 'LLVMCountStructElementTypes)

(cffi:defcfun ("LLVMGetStructElementTypes" LLVMGetStructElementTypes) :void
  (StructTy :pointer)
  (Dest :pointer))

(cl:export 'LLVMGetStructElementTypes)

(cffi:defcfun ("LLVMIsPackedStruct" LLVMIsPackedStruct) :int
  (StructTy :pointer))

(cl:export 'LLVMIsPackedStruct)

(cffi:defcfun ("LLVMIsOpaqueStruct" LLVMIsOpaqueStruct) :int
  (StructTy :pointer))

(cl:export 'LLVMIsOpaqueStruct)

(cffi:defcfun ("LLVMGetElementType" LLVMGetElementType) :pointer
  (Ty :pointer))

(cl:export 'LLVMGetElementType)

(cffi:defcfun ("LLVMArrayType" LLVMArrayType) :pointer
  (ElementType :pointer)
  (ElementCount :unsigned-int))

(cl:export 'LLVMArrayType)

(cffi:defcfun ("LLVMGetArrayLength" LLVMGetArrayLength) :unsigned-int
  (ArrayTy :pointer))

(cl:export 'LLVMGetArrayLength)

(cffi:defcfun ("LLVMPointerType" LLVMPointerType) :pointer
  (ElementType :pointer)
  (AddressSpace :unsigned-int))

(cl:export 'LLVMPointerType)

(cffi:defcfun ("LLVMGetPointerAddressSpace" LLVMGetPointerAddressSpace) :unsigned-int
  (PointerTy :pointer))

(cl:export 'LLVMGetPointerAddressSpace)

(cffi:defcfun ("LLVMVectorType" LLVMVectorType) :pointer
  (ElementType :pointer)
  (ElementCount :unsigned-int))

(cl:export 'LLVMVectorType)

(cffi:defcfun ("LLVMGetVectorSize" LLVMGetVectorSize) :unsigned-int
  (VectorTy :pointer))

(cl:export 'LLVMGetVectorSize)

(cffi:defcfun ("LLVMVoidTypeInContext" LLVMVoidTypeInContext) :pointer
  (C :pointer))

(cl:export 'LLVMVoidTypeInContext)

(cffi:defcfun ("LLVMLabelTypeInContext" LLVMLabelTypeInContext) :pointer
  (C :pointer))

(cl:export 'LLVMLabelTypeInContext)

(cffi:defcfun ("LLVMX86MMXTypeInContext" LLVMX86MMXTypeInContext) :pointer
  (C :pointer))

(cl:export 'LLVMX86MMXTypeInContext)

(cffi:defcfun ("LLVMVoidType" LLVMVoidType) :pointer)

(cl:export 'LLVMVoidType)

(cffi:defcfun ("LLVMLabelType" LLVMLabelType) :pointer)

(cl:export 'LLVMLabelType)

(cffi:defcfun ("LLVMX86MMXType" LLVMX86MMXType) :pointer)

(cl:export 'LLVMX86MMXType)

(cffi:defcfun ("LLVMTypeOf" LLVMTypeOf) :pointer
  (Val :pointer))

(cl:export 'LLVMTypeOf)

(cffi:defcfun ("LLVMGetValueName" LLVMGetValueName) :string
  (Val :pointer))

(cl:export 'LLVMGetValueName)

(cffi:defcfun ("LLVMSetValueName" LLVMSetValueName) :void
  (Val :pointer)
  (Name :string))

(cl:export 'LLVMSetValueName)

(cffi:defcfun ("LLVMDumpValue" LLVMDumpValue) :void
  (Val :pointer))

(cl:export 'LLVMDumpValue)

(cffi:defcfun ("LLVMPrintValueToString" LLVMPrintValueToString) :string
  (Val :pointer))

(cl:export 'LLVMPrintValueToString)

(cffi:defcfun ("LLVMReplaceAllUsesWith" LLVMReplaceAllUsesWith) :void
  (OldVal :pointer)
  (NewVal :pointer))

(cl:export 'LLVMReplaceAllUsesWith)

(cffi:defcfun ("LLVMIsConstant" LLVMIsConstant) :int
  (Val :pointer))

(cl:export 'LLVMIsConstant)

(cffi:defcfun ("LLVMIsUndef" LLVMIsUndef) :int
  (Val :pointer))

(cl:export 'LLVMIsUndef)

(cffi:defcfun ("LLVMIsAArgument" LLVMIsAArgument) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAArgument)

(cffi:defcfun ("LLVMIsABasicBlock" LLVMIsABasicBlock) :pointer
  (Val :pointer))

(cl:export 'LLVMIsABasicBlock)

(cffi:defcfun ("LLVMIsAInlineAsm" LLVMIsAInlineAsm) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAInlineAsm)

(cffi:defcfun ("LLVMIsAMDNode" LLVMIsAMDNode) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAMDNode)

(cffi:defcfun ("LLVMIsAMDString" LLVMIsAMDString) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAMDString)

(cffi:defcfun ("LLVMIsAUser" LLVMIsAUser) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAUser)

(cffi:defcfun ("LLVMIsAConstant" LLVMIsAConstant) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAConstant)

(cffi:defcfun ("LLVMIsABlockAddress" LLVMIsABlockAddress) :pointer
  (Val :pointer))

(cl:export 'LLVMIsABlockAddress)

(cffi:defcfun ("LLVMIsAConstantAggregateZero" LLVMIsAConstantAggregateZero) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAConstantAggregateZero)

(cffi:defcfun ("LLVMIsAConstantArray" LLVMIsAConstantArray) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAConstantArray)

(cffi:defcfun ("LLVMIsAConstantDataSequential" LLVMIsAConstantDataSequential) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAConstantDataSequential)

(cffi:defcfun ("LLVMIsAConstantDataArray" LLVMIsAConstantDataArray) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAConstantDataArray)

(cffi:defcfun ("LLVMIsAConstantDataVector" LLVMIsAConstantDataVector) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAConstantDataVector)

(cffi:defcfun ("LLVMIsAConstantExpr" LLVMIsAConstantExpr) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAConstantExpr)

(cffi:defcfun ("LLVMIsAConstantFP" LLVMIsAConstantFP) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAConstantFP)

(cffi:defcfun ("LLVMIsAConstantInt" LLVMIsAConstantInt) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAConstantInt)

(cffi:defcfun ("LLVMIsAConstantPointerNull" LLVMIsAConstantPointerNull) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAConstantPointerNull)

(cffi:defcfun ("LLVMIsAConstantStruct" LLVMIsAConstantStruct) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAConstantStruct)

(cffi:defcfun ("LLVMIsAConstantVector" LLVMIsAConstantVector) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAConstantVector)

(cffi:defcfun ("LLVMIsAGlobalValue" LLVMIsAGlobalValue) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAGlobalValue)

(cffi:defcfun ("LLVMIsAFunction" LLVMIsAFunction) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAFunction)

(cffi:defcfun ("LLVMIsAGlobalAlias" LLVMIsAGlobalAlias) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAGlobalAlias)

(cffi:defcfun ("LLVMIsAGlobalVariable" LLVMIsAGlobalVariable) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAGlobalVariable)

(cffi:defcfun ("LLVMIsAUndefValue" LLVMIsAUndefValue) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAUndefValue)

(cffi:defcfun ("LLVMIsAInstruction" LLVMIsAInstruction) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAInstruction)

(cffi:defcfun ("LLVMIsABinaryOperator" LLVMIsABinaryOperator) :pointer
  (Val :pointer))

(cl:export 'LLVMIsABinaryOperator)

(cffi:defcfun ("LLVMIsACallInst" LLVMIsACallInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsACallInst)

(cffi:defcfun ("LLVMIsAIntrinsicInst" LLVMIsAIntrinsicInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAIntrinsicInst)

(cffi:defcfun ("LLVMIsADbgInfoIntrinsic" LLVMIsADbgInfoIntrinsic) :pointer
  (Val :pointer))

(cl:export 'LLVMIsADbgInfoIntrinsic)

(cffi:defcfun ("LLVMIsADbgDeclareInst" LLVMIsADbgDeclareInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsADbgDeclareInst)

(cffi:defcfun ("LLVMIsAMemIntrinsic" LLVMIsAMemIntrinsic) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAMemIntrinsic)

(cffi:defcfun ("LLVMIsAMemCpyInst" LLVMIsAMemCpyInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAMemCpyInst)

(cffi:defcfun ("LLVMIsAMemMoveInst" LLVMIsAMemMoveInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAMemMoveInst)

(cffi:defcfun ("LLVMIsAMemSetInst" LLVMIsAMemSetInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAMemSetInst)

(cffi:defcfun ("LLVMIsACmpInst" LLVMIsACmpInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsACmpInst)

(cffi:defcfun ("LLVMIsAFCmpInst" LLVMIsAFCmpInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAFCmpInst)

(cffi:defcfun ("LLVMIsAICmpInst" LLVMIsAICmpInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAICmpInst)

(cffi:defcfun ("LLVMIsAExtractElementInst" LLVMIsAExtractElementInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAExtractElementInst)

(cffi:defcfun ("LLVMIsAGetElementPtrInst" LLVMIsAGetElementPtrInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAGetElementPtrInst)

(cffi:defcfun ("LLVMIsAInsertElementInst" LLVMIsAInsertElementInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAInsertElementInst)

(cffi:defcfun ("LLVMIsAInsertValueInst" LLVMIsAInsertValueInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAInsertValueInst)

(cffi:defcfun ("LLVMIsALandingPadInst" LLVMIsALandingPadInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsALandingPadInst)

(cffi:defcfun ("LLVMIsAPHINode" LLVMIsAPHINode) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAPHINode)

(cffi:defcfun ("LLVMIsASelectInst" LLVMIsASelectInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsASelectInst)

(cffi:defcfun ("LLVMIsAShuffleVectorInst" LLVMIsAShuffleVectorInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAShuffleVectorInst)

(cffi:defcfun ("LLVMIsAStoreInst" LLVMIsAStoreInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAStoreInst)

(cffi:defcfun ("LLVMIsATerminatorInst" LLVMIsATerminatorInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsATerminatorInst)

(cffi:defcfun ("LLVMIsABranchInst" LLVMIsABranchInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsABranchInst)

(cffi:defcfun ("LLVMIsAIndirectBrInst" LLVMIsAIndirectBrInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAIndirectBrInst)

(cffi:defcfun ("LLVMIsAInvokeInst" LLVMIsAInvokeInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAInvokeInst)

(cffi:defcfun ("LLVMIsAReturnInst" LLVMIsAReturnInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAReturnInst)

(cffi:defcfun ("LLVMIsASwitchInst" LLVMIsASwitchInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsASwitchInst)

(cffi:defcfun ("LLVMIsAUnreachableInst" LLVMIsAUnreachableInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAUnreachableInst)

(cffi:defcfun ("LLVMIsAResumeInst" LLVMIsAResumeInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAResumeInst)

(cffi:defcfun ("LLVMIsAUnaryInstruction" LLVMIsAUnaryInstruction) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAUnaryInstruction)

(cffi:defcfun ("LLVMIsAAllocaInst" LLVMIsAAllocaInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAAllocaInst)

(cffi:defcfun ("LLVMIsACastInst" LLVMIsACastInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsACastInst)

(cffi:defcfun ("LLVMIsAAddrSpaceCastInst" LLVMIsAAddrSpaceCastInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAAddrSpaceCastInst)

(cffi:defcfun ("LLVMIsABitCastInst" LLVMIsABitCastInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsABitCastInst)

(cffi:defcfun ("LLVMIsAFPExtInst" LLVMIsAFPExtInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAFPExtInst)

(cffi:defcfun ("LLVMIsAFPToSIInst" LLVMIsAFPToSIInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAFPToSIInst)

(cffi:defcfun ("LLVMIsAFPToUIInst" LLVMIsAFPToUIInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAFPToUIInst)

(cffi:defcfun ("LLVMIsAFPTruncInst" LLVMIsAFPTruncInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAFPTruncInst)

(cffi:defcfun ("LLVMIsAIntToPtrInst" LLVMIsAIntToPtrInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAIntToPtrInst)

(cffi:defcfun ("LLVMIsAPtrToIntInst" LLVMIsAPtrToIntInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAPtrToIntInst)

(cffi:defcfun ("LLVMIsASExtInst" LLVMIsASExtInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsASExtInst)

(cffi:defcfun ("LLVMIsASIToFPInst" LLVMIsASIToFPInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsASIToFPInst)

(cffi:defcfun ("LLVMIsATruncInst" LLVMIsATruncInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsATruncInst)

(cffi:defcfun ("LLVMIsAUIToFPInst" LLVMIsAUIToFPInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAUIToFPInst)

(cffi:defcfun ("LLVMIsAZExtInst" LLVMIsAZExtInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAZExtInst)

(cffi:defcfun ("LLVMIsAExtractValueInst" LLVMIsAExtractValueInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAExtractValueInst)

(cffi:defcfun ("LLVMIsALoadInst" LLVMIsALoadInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsALoadInst)

(cffi:defcfun ("LLVMIsAVAArgInst" LLVMIsAVAArgInst) :pointer
  (Val :pointer))

(cl:export 'LLVMIsAVAArgInst)

(cffi:defcfun ("LLVMGetFirstUse" LLVMGetFirstUse) :pointer
  (Val :pointer))

(cl:export 'LLVMGetFirstUse)

(cffi:defcfun ("LLVMGetNextUse" LLVMGetNextUse) :pointer
  (U :pointer))

(cl:export 'LLVMGetNextUse)

(cffi:defcfun ("LLVMGetUser" LLVMGetUser) :pointer
  (U :pointer))

(cl:export 'LLVMGetUser)

(cffi:defcfun ("LLVMGetUsedValue" LLVMGetUsedValue) :pointer
  (U :pointer))

(cl:export 'LLVMGetUsedValue)

(cffi:defcfun ("LLVMGetOperand" LLVMGetOperand) :pointer
  (Val :pointer)
  (Index :unsigned-int))

(cl:export 'LLVMGetOperand)

(cffi:defcfun ("LLVMSetOperand" LLVMSetOperand) :void
  (User :pointer)
  (Index :unsigned-int)
  (Val :pointer))

(cl:export 'LLVMSetOperand)

(cffi:defcfun ("LLVMGetNumOperands" LLVMGetNumOperands) :int
  (Val :pointer))

(cl:export 'LLVMGetNumOperands)

(cffi:defcfun ("LLVMConstNull" LLVMConstNull) :pointer
  (Ty :pointer))

(cl:export 'LLVMConstNull)

(cffi:defcfun ("LLVMConstAllOnes" LLVMConstAllOnes) :pointer
  (Ty :pointer))

(cl:export 'LLVMConstAllOnes)

(cffi:defcfun ("LLVMGetUndef" LLVMGetUndef) :pointer
  (Ty :pointer))

(cl:export 'LLVMGetUndef)

(cffi:defcfun ("LLVMIsNull" LLVMIsNull) :int
  (Val :pointer))

(cl:export 'LLVMIsNull)

(cffi:defcfun ("LLVMConstPointerNull" LLVMConstPointerNull) :pointer
  (Ty :pointer))

(cl:export 'LLVMConstPointerNull)

(cffi:defcfun ("LLVMConstInt" LLVMConstInt) :pointer
  (IntTy :pointer)
  (N :unsigned-long-long)
  (SignExtend :int))

(cl:export 'LLVMConstInt)

(cffi:defcfun ("LLVMConstIntOfArbitraryPrecision" LLVMConstIntOfArbitraryPrecision) :pointer
  (IntTy :pointer)
  (NumWords :unsigned-int)
  (Words :pointer))

(cl:export 'LLVMConstIntOfArbitraryPrecision)

(cffi:defcfun ("LLVMConstIntOfString" LLVMConstIntOfString) :pointer
  (IntTy :pointer)
  (Text :string)
  (Radix :pointer))

(cl:export 'LLVMConstIntOfString)

(cffi:defcfun ("LLVMConstIntOfStringAndSize" LLVMConstIntOfStringAndSize) :pointer
  (IntTy :pointer)
  (Text :string)
  (SLen :unsigned-int)
  (Radix :pointer))

(cl:export 'LLVMConstIntOfStringAndSize)

(cffi:defcfun ("LLVMConstReal" LLVMConstReal) :pointer
  (RealTy :pointer)
  (N :double))

(cl:export 'LLVMConstReal)

(cffi:defcfun ("LLVMConstRealOfString" LLVMConstRealOfString) :pointer
  (RealTy :pointer)
  (Text :string))

(cl:export 'LLVMConstRealOfString)

(cffi:defcfun ("LLVMConstRealOfStringAndSize" LLVMConstRealOfStringAndSize) :pointer
  (RealTy :pointer)
  (Text :string)
  (SLen :unsigned-int))

(cl:export 'LLVMConstRealOfStringAndSize)

(cffi:defcfun ("LLVMConstIntGetZExtValue" LLVMConstIntGetZExtValue) :unsigned-long-long
  (ConstantVal :pointer))

(cl:export 'LLVMConstIntGetZExtValue)

(cffi:defcfun ("LLVMConstIntGetSExtValue" LLVMConstIntGetSExtValue) :long-long
  (ConstantVal :pointer))

(cl:export 'LLVMConstIntGetSExtValue)

(cffi:defcfun ("LLVMConstStringInContext" LLVMConstStringInContext) :pointer
  (C :pointer)
  (Str :string)
  (Length :unsigned-int)
  (DontNullTerminate :int))

(cl:export 'LLVMConstStringInContext)

(cffi:defcfun ("LLVMConstString" LLVMConstString) :pointer
  (Str :string)
  (Length :unsigned-int)
  (DontNullTerminate :int))

(cl:export 'LLVMConstString)

(cffi:defcfun ("LLVMConstStructInContext" LLVMConstStructInContext) :pointer
  (C :pointer)
  (ConstantVals :pointer)
  (Count :unsigned-int)
  (Packed :int))

(cl:export 'LLVMConstStructInContext)

(cffi:defcfun ("LLVMConstStruct" LLVMConstStruct) :pointer
  (ConstantVals :pointer)
  (Count :unsigned-int)
  (Packed :int))

(cl:export 'LLVMConstStruct)

(cffi:defcfun ("LLVMConstArray" LLVMConstArray) :pointer
  (ElementTy :pointer)
  (ConstantVals :pointer)
  (Length :unsigned-int))

(cl:export 'LLVMConstArray)

(cffi:defcfun ("LLVMConstNamedStruct" LLVMConstNamedStruct) :pointer
  (StructTy :pointer)
  (ConstantVals :pointer)
  (Count :unsigned-int))

(cl:export 'LLVMConstNamedStruct)

(cffi:defcfun ("LLVMConstVector" LLVMConstVector) :pointer
  (ScalarConstantVals :pointer)
  (Size :unsigned-int))

(cl:export 'LLVMConstVector)

(cffi:defcfun ("LLVMGetConstOpcode" LLVMGetConstOpcode) LLVMOpcode
  (ConstantVal :pointer))

(cl:export 'LLVMGetConstOpcode)

(cffi:defcfun ("LLVMAlignOf" LLVMAlignOf) :pointer
  (Ty :pointer))

(cl:export 'LLVMAlignOf)

(cffi:defcfun ("LLVMSizeOf" LLVMSizeOf) :pointer
  (Ty :pointer))

(cl:export 'LLVMSizeOf)

(cffi:defcfun ("LLVMConstNeg" LLVMConstNeg) :pointer
  (ConstantVal :pointer))

(cl:export 'LLVMConstNeg)

(cffi:defcfun ("LLVMConstNSWNeg" LLVMConstNSWNeg) :pointer
  (ConstantVal :pointer))

(cl:export 'LLVMConstNSWNeg)

(cffi:defcfun ("LLVMConstNUWNeg" LLVMConstNUWNeg) :pointer
  (ConstantVal :pointer))

(cl:export 'LLVMConstNUWNeg)

(cffi:defcfun ("LLVMConstFNeg" LLVMConstFNeg) :pointer
  (ConstantVal :pointer))

(cl:export 'LLVMConstFNeg)

(cffi:defcfun ("LLVMConstNot" LLVMConstNot) :pointer
  (ConstantVal :pointer))

(cl:export 'LLVMConstNot)

(cffi:defcfun ("LLVMConstAdd" LLVMConstAdd) :pointer
  (LHSConstant :pointer)
  (RHSConstant :pointer))

(cl:export 'LLVMConstAdd)

(cffi:defcfun ("LLVMConstNSWAdd" LLVMConstNSWAdd) :pointer
  (LHSConstant :pointer)
  (RHSConstant :pointer))

(cl:export 'LLVMConstNSWAdd)

(cffi:defcfun ("LLVMConstNUWAdd" LLVMConstNUWAdd) :pointer
  (LHSConstant :pointer)
  (RHSConstant :pointer))

(cl:export 'LLVMConstNUWAdd)

(cffi:defcfun ("LLVMConstFAdd" LLVMConstFAdd) :pointer
  (LHSConstant :pointer)
  (RHSConstant :pointer))

(cl:export 'LLVMConstFAdd)

(cffi:defcfun ("LLVMConstSub" LLVMConstSub) :pointer
  (LHSConstant :pointer)
  (RHSConstant :pointer))

(cl:export 'LLVMConstSub)

(cffi:defcfun ("LLVMConstNSWSub" LLVMConstNSWSub) :pointer
  (LHSConstant :pointer)
  (RHSConstant :pointer))

(cl:export 'LLVMConstNSWSub)

(cffi:defcfun ("LLVMConstNUWSub" LLVMConstNUWSub) :pointer
  (LHSConstant :pointer)
  (RHSConstant :pointer))

(cl:export 'LLVMConstNUWSub)

(cffi:defcfun ("LLVMConstFSub" LLVMConstFSub) :pointer
  (LHSConstant :pointer)
  (RHSConstant :pointer))

(cl:export 'LLVMConstFSub)

(cffi:defcfun ("LLVMConstMul" LLVMConstMul) :pointer
  (LHSConstant :pointer)
  (RHSConstant :pointer))

(cl:export 'LLVMConstMul)

(cffi:defcfun ("LLVMConstNSWMul" LLVMConstNSWMul) :pointer
  (LHSConstant :pointer)
  (RHSConstant :pointer))

(cl:export 'LLVMConstNSWMul)

(cffi:defcfun ("LLVMConstNUWMul" LLVMConstNUWMul) :pointer
  (LHSConstant :pointer)
  (RHSConstant :pointer))

(cl:export 'LLVMConstNUWMul)

(cffi:defcfun ("LLVMConstFMul" LLVMConstFMul) :pointer
  (LHSConstant :pointer)
  (RHSConstant :pointer))

(cl:export 'LLVMConstFMul)

(cffi:defcfun ("LLVMConstUDiv" LLVMConstUDiv) :pointer
  (LHSConstant :pointer)
  (RHSConstant :pointer))

(cl:export 'LLVMConstUDiv)

(cffi:defcfun ("LLVMConstSDiv" LLVMConstSDiv) :pointer
  (LHSConstant :pointer)
  (RHSConstant :pointer))

(cl:export 'LLVMConstSDiv)

(cffi:defcfun ("LLVMConstExactSDiv" LLVMConstExactSDiv) :pointer
  (LHSConstant :pointer)
  (RHSConstant :pointer))

(cl:export 'LLVMConstExactSDiv)

(cffi:defcfun ("LLVMConstFDiv" LLVMConstFDiv) :pointer
  (LHSConstant :pointer)
  (RHSConstant :pointer))

(cl:export 'LLVMConstFDiv)

(cffi:defcfun ("LLVMConstURem" LLVMConstURem) :pointer
  (LHSConstant :pointer)
  (RHSConstant :pointer))

(cl:export 'LLVMConstURem)

(cffi:defcfun ("LLVMConstSRem" LLVMConstSRem) :pointer
  (LHSConstant :pointer)
  (RHSConstant :pointer))

(cl:export 'LLVMConstSRem)

(cffi:defcfun ("LLVMConstFRem" LLVMConstFRem) :pointer
  (LHSConstant :pointer)
  (RHSConstant :pointer))

(cl:export 'LLVMConstFRem)

(cffi:defcfun ("LLVMConstAnd" LLVMConstAnd) :pointer
  (LHSConstant :pointer)
  (RHSConstant :pointer))

(cl:export 'LLVMConstAnd)

(cffi:defcfun ("LLVMConstOr" LLVMConstOr) :pointer
  (LHSConstant :pointer)
  (RHSConstant :pointer))

(cl:export 'LLVMConstOr)

(cffi:defcfun ("LLVMConstXor" LLVMConstXor) :pointer
  (LHSConstant :pointer)
  (RHSConstant :pointer))

(cl:export 'LLVMConstXor)

(cffi:defcfun ("LLVMConstICmp" LLVMConstICmp) :pointer
  (Predicate LLVMIntPredicate)
  (LHSConstant :pointer)
  (RHSConstant :pointer))

(cl:export 'LLVMConstICmp)

(cffi:defcfun ("LLVMConstFCmp" LLVMConstFCmp) :pointer
  (Predicate LLVMRealPredicate)
  (LHSConstant :pointer)
  (RHSConstant :pointer))

(cl:export 'LLVMConstFCmp)

(cffi:defcfun ("LLVMConstShl" LLVMConstShl) :pointer
  (LHSConstant :pointer)
  (RHSConstant :pointer))

(cl:export 'LLVMConstShl)

(cffi:defcfun ("LLVMConstLShr" LLVMConstLShr) :pointer
  (LHSConstant :pointer)
  (RHSConstant :pointer))

(cl:export 'LLVMConstLShr)

(cffi:defcfun ("LLVMConstAShr" LLVMConstAShr) :pointer
  (LHSConstant :pointer)
  (RHSConstant :pointer))

(cl:export 'LLVMConstAShr)

(cffi:defcfun ("LLVMConstGEP" LLVMConstGEP) :pointer
  (ConstantVal :pointer)
  (ConstantIndices :pointer)
  (NumIndices :unsigned-int))

(cl:export 'LLVMConstGEP)

(cffi:defcfun ("LLVMConstInBoundsGEP" LLVMConstInBoundsGEP) :pointer
  (ConstantVal :pointer)
  (ConstantIndices :pointer)
  (NumIndices :unsigned-int))

(cl:export 'LLVMConstInBoundsGEP)

(cffi:defcfun ("LLVMConstTrunc" LLVMConstTrunc) :pointer
  (ConstantVal :pointer)
  (ToType :pointer))

(cl:export 'LLVMConstTrunc)

(cffi:defcfun ("LLVMConstSExt" LLVMConstSExt) :pointer
  (ConstantVal :pointer)
  (ToType :pointer))

(cl:export 'LLVMConstSExt)

(cffi:defcfun ("LLVMConstZExt" LLVMConstZExt) :pointer
  (ConstantVal :pointer)
  (ToType :pointer))

(cl:export 'LLVMConstZExt)

(cffi:defcfun ("LLVMConstFPTrunc" LLVMConstFPTrunc) :pointer
  (ConstantVal :pointer)
  (ToType :pointer))

(cl:export 'LLVMConstFPTrunc)

(cffi:defcfun ("LLVMConstFPExt" LLVMConstFPExt) :pointer
  (ConstantVal :pointer)
  (ToType :pointer))

(cl:export 'LLVMConstFPExt)

(cffi:defcfun ("LLVMConstUIToFP" LLVMConstUIToFP) :pointer
  (ConstantVal :pointer)
  (ToType :pointer))

(cl:export 'LLVMConstUIToFP)

(cffi:defcfun ("LLVMConstSIToFP" LLVMConstSIToFP) :pointer
  (ConstantVal :pointer)
  (ToType :pointer))

(cl:export 'LLVMConstSIToFP)

(cffi:defcfun ("LLVMConstFPToUI" LLVMConstFPToUI) :pointer
  (ConstantVal :pointer)
  (ToType :pointer))

(cl:export 'LLVMConstFPToUI)

(cffi:defcfun ("LLVMConstFPToSI" LLVMConstFPToSI) :pointer
  (ConstantVal :pointer)
  (ToType :pointer))

(cl:export 'LLVMConstFPToSI)

(cffi:defcfun ("LLVMConstPtrToInt" LLVMConstPtrToInt) :pointer
  (ConstantVal :pointer)
  (ToType :pointer))

(cl:export 'LLVMConstPtrToInt)

(cffi:defcfun ("LLVMConstIntToPtr" LLVMConstIntToPtr) :pointer
  (ConstantVal :pointer)
  (ToType :pointer))

(cl:export 'LLVMConstIntToPtr)

(cffi:defcfun ("LLVMConstBitCast" LLVMConstBitCast) :pointer
  (ConstantVal :pointer)
  (ToType :pointer))

(cl:export 'LLVMConstBitCast)

(cffi:defcfun ("LLVMConstAddrSpaceCast" LLVMConstAddrSpaceCast) :pointer
  (ConstantVal :pointer)
  (ToType :pointer))

(cl:export 'LLVMConstAddrSpaceCast)

(cffi:defcfun ("LLVMConstZExtOrBitCast" LLVMConstZExtOrBitCast) :pointer
  (ConstantVal :pointer)
  (ToType :pointer))

(cl:export 'LLVMConstZExtOrBitCast)

(cffi:defcfun ("LLVMConstSExtOrBitCast" LLVMConstSExtOrBitCast) :pointer
  (ConstantVal :pointer)
  (ToType :pointer))

(cl:export 'LLVMConstSExtOrBitCast)

(cffi:defcfun ("LLVMConstTruncOrBitCast" LLVMConstTruncOrBitCast) :pointer
  (ConstantVal :pointer)
  (ToType :pointer))

(cl:export 'LLVMConstTruncOrBitCast)

(cffi:defcfun ("LLVMConstPointerCast" LLVMConstPointerCast) :pointer
  (ConstantVal :pointer)
  (ToType :pointer))

(cl:export 'LLVMConstPointerCast)

(cffi:defcfun ("LLVMConstIntCast" LLVMConstIntCast) :pointer
  (ConstantVal :pointer)
  (ToType :pointer)
  (isSigned :int))

(cl:export 'LLVMConstIntCast)

(cffi:defcfun ("LLVMConstFPCast" LLVMConstFPCast) :pointer
  (ConstantVal :pointer)
  (ToType :pointer))

(cl:export 'LLVMConstFPCast)

(cffi:defcfun ("LLVMConstSelect" LLVMConstSelect) :pointer
  (ConstantCondition :pointer)
  (ConstantIfTrue :pointer)
  (ConstantIfFalse :pointer))

(cl:export 'LLVMConstSelect)

(cffi:defcfun ("LLVMConstExtractElement" LLVMConstExtractElement) :pointer
  (VectorConstant :pointer)
  (IndexConstant :pointer))

(cl:export 'LLVMConstExtractElement)

(cffi:defcfun ("LLVMConstInsertElement" LLVMConstInsertElement) :pointer
  (VectorConstant :pointer)
  (ElementValueConstant :pointer)
  (IndexConstant :pointer))

(cl:export 'LLVMConstInsertElement)

(cffi:defcfun ("LLVMConstShuffleVector" LLVMConstShuffleVector) :pointer
  (VectorAConstant :pointer)
  (VectorBConstant :pointer)
  (MaskConstant :pointer))

(cl:export 'LLVMConstShuffleVector)

(cffi:defcfun ("LLVMConstExtractValue" LLVMConstExtractValue) :pointer
  (AggConstant :pointer)
  (IdxList :pointer)
  (NumIdx :unsigned-int))

(cl:export 'LLVMConstExtractValue)

(cffi:defcfun ("LLVMConstInsertValue" LLVMConstInsertValue) :pointer
  (AggConstant :pointer)
  (ElementValueConstant :pointer)
  (IdxList :pointer)
  (NumIdx :unsigned-int))

(cl:export 'LLVMConstInsertValue)

(cffi:defcfun ("LLVMConstInlineAsm" LLVMConstInlineAsm) :pointer
  (Ty :pointer)
  (AsmString :string)
  (Constraints :string)
  (HasSideEffects :int)
  (IsAlignStack :int))

(cl:export 'LLVMConstInlineAsm)

(cffi:defcfun ("LLVMBlockAddress" LLVMBlockAddress) :pointer
  (F :pointer)
  (BB :pointer))

(cl:export 'LLVMBlockAddress)

(cffi:defcfun ("LLVMGetGlobalParent" LLVMGetGlobalParent) :pointer
  (Global :pointer))

(cl:export 'LLVMGetGlobalParent)

(cffi:defcfun ("LLVMIsDeclaration" LLVMIsDeclaration) :int
  (Global :pointer))

(cl:export 'LLVMIsDeclaration)

(cffi:defcfun ("LLVMGetLinkage" LLVMGetLinkage) LLVMLinkage
  (Global :pointer))

(cl:export 'LLVMGetLinkage)

(cffi:defcfun ("LLVMSetLinkage" LLVMSetLinkage) :void
  (Global :pointer)
  (Linkage LLVMLinkage))

(cl:export 'LLVMSetLinkage)

(cffi:defcfun ("LLVMGetSection" LLVMGetSection) :string
  (Global :pointer))

(cl:export 'LLVMGetSection)

(cffi:defcfun ("LLVMSetSection" LLVMSetSection) :void
  (Global :pointer)
  (Section :string))

(cl:export 'LLVMSetSection)

(cffi:defcfun ("LLVMGetVisibility" LLVMGetVisibility) LLVMVisibility
  (Global :pointer))

(cl:export 'LLVMGetVisibility)

(cffi:defcfun ("LLVMSetVisibility" LLVMSetVisibility) :void
  (Global :pointer)
  (Viz LLVMVisibility))

(cl:export 'LLVMSetVisibility)

(cffi:defcfun ("LLVMGetAlignment" LLVMGetAlignment) :unsigned-int
  (V :pointer))

(cl:export 'LLVMGetAlignment)

(cffi:defcfun ("LLVMSetAlignment" LLVMSetAlignment) :void
  (V :pointer)
  (Bytes :unsigned-int))

(cl:export 'LLVMSetAlignment)

(cffi:defcfun ("LLVMAddGlobal" LLVMAddGlobal) :pointer
  (M :pointer)
  (Ty :pointer)
  (Name :string))

(cl:export 'LLVMAddGlobal)

(cffi:defcfun ("LLVMAddGlobalInAddressSpace" LLVMAddGlobalInAddressSpace) :pointer
  (M :pointer)
  (Ty :pointer)
  (Name :string)
  (AddressSpace :unsigned-int))

(cl:export 'LLVMAddGlobalInAddressSpace)

(cffi:defcfun ("LLVMGetNamedGlobal" LLVMGetNamedGlobal) :pointer
  (M :pointer)
  (Name :string))

(cl:export 'LLVMGetNamedGlobal)

(cffi:defcfun ("LLVMGetFirstGlobal" LLVMGetFirstGlobal) :pointer
  (M :pointer))

(cl:export 'LLVMGetFirstGlobal)

(cffi:defcfun ("LLVMGetLastGlobal" LLVMGetLastGlobal) :pointer
  (M :pointer))

(cl:export 'LLVMGetLastGlobal)

(cffi:defcfun ("LLVMGetNextGlobal" LLVMGetNextGlobal) :pointer
  (GlobalVar :pointer))

(cl:export 'LLVMGetNextGlobal)

(cffi:defcfun ("LLVMGetPreviousGlobal" LLVMGetPreviousGlobal) :pointer
  (GlobalVar :pointer))

(cl:export 'LLVMGetPreviousGlobal)

(cffi:defcfun ("LLVMDeleteGlobal" LLVMDeleteGlobal) :void
  (GlobalVar :pointer))

(cl:export 'LLVMDeleteGlobal)

(cffi:defcfun ("LLVMGetInitializer" LLVMGetInitializer) :pointer
  (GlobalVar :pointer))

(cl:export 'LLVMGetInitializer)

(cffi:defcfun ("LLVMSetInitializer" LLVMSetInitializer) :void
  (GlobalVar :pointer)
  (ConstantVal :pointer))

(cl:export 'LLVMSetInitializer)

(cffi:defcfun ("LLVMIsThreadLocal" LLVMIsThreadLocal) :int
  (GlobalVar :pointer))

(cl:export 'LLVMIsThreadLocal)

(cffi:defcfun ("LLVMSetThreadLocal" LLVMSetThreadLocal) :void
  (GlobalVar :pointer)
  (IsThreadLocal :int))

(cl:export 'LLVMSetThreadLocal)

(cffi:defcfun ("LLVMIsGlobalConstant" LLVMIsGlobalConstant) :int
  (GlobalVar :pointer))

(cl:export 'LLVMIsGlobalConstant)

(cffi:defcfun ("LLVMSetGlobalConstant" LLVMSetGlobalConstant) :void
  (GlobalVar :pointer)
  (IsConstant :int))

(cl:export 'LLVMSetGlobalConstant)

(cffi:defcfun ("LLVMGetThreadLocalMode" LLVMGetThreadLocalMode) LLVMThreadLocalMode
  (GlobalVar :pointer))

(cl:export 'LLVMGetThreadLocalMode)

(cffi:defcfun ("LLVMSetThreadLocalMode" LLVMSetThreadLocalMode) :void
  (GlobalVar :pointer)
  (Mode LLVMThreadLocalMode))

(cl:export 'LLVMSetThreadLocalMode)

(cffi:defcfun ("LLVMIsExternallyInitialized" LLVMIsExternallyInitialized) :int
  (GlobalVar :pointer))

(cl:export 'LLVMIsExternallyInitialized)

(cffi:defcfun ("LLVMSetExternallyInitialized" LLVMSetExternallyInitialized) :void
  (GlobalVar :pointer)
  (IsExtInit :int))

(cl:export 'LLVMSetExternallyInitialized)

(cffi:defcfun ("LLVMAddAlias" LLVMAddAlias) :pointer
  (M :pointer)
  (Ty :pointer)
  (Aliasee :pointer)
  (Name :string))

(cl:export 'LLVMAddAlias)

(cffi:defcfun ("LLVMDeleteFunction" LLVMDeleteFunction) :void
  (Fn :pointer))

(cl:export 'LLVMDeleteFunction)

(cffi:defcfun ("LLVMGetIntrinsicID" LLVMGetIntrinsicID) :unsigned-int
  (Fn :pointer))

(cl:export 'LLVMGetIntrinsicID)

(cffi:defcfun ("LLVMGetFunctionCallConv" LLVMGetFunctionCallConv) :unsigned-int
  (Fn :pointer))

(cl:export 'LLVMGetFunctionCallConv)

(cffi:defcfun ("LLVMSetFunctionCallConv" LLVMSetFunctionCallConv) :void
  (Fn :pointer)
  (CC :unsigned-int))

(cl:export 'LLVMSetFunctionCallConv)

(cffi:defcfun ("LLVMGetGC" LLVMGetGC) :string
  (Fn :pointer))

(cl:export 'LLVMGetGC)

(cffi:defcfun ("LLVMSetGC" LLVMSetGC) :void
  (Fn :pointer)
  (Name :string))

(cl:export 'LLVMSetGC)

(cffi:defcfun ("LLVMAddFunctionAttr" LLVMAddFunctionAttr) :void
  (Fn :pointer)
  (PA LLVMAttribute))

(cl:export 'LLVMAddFunctionAttr)

(cffi:defcfun ("LLVMAddTargetDependentFunctionAttr" LLVMAddTargetDependentFunctionAttr) :void
  (Fn :pointer)
  (A :string)
  (V :string))

(cl:export 'LLVMAddTargetDependentFunctionAttr)

(cffi:defcfun ("LLVMGetFunctionAttr" LLVMGetFunctionAttr) LLVMAttribute
  (Fn :pointer))

(cl:export 'LLVMGetFunctionAttr)

(cffi:defcfun ("LLVMRemoveFunctionAttr" LLVMRemoveFunctionAttr) :void
  (Fn :pointer)
  (PA LLVMAttribute))

(cl:export 'LLVMRemoveFunctionAttr)

(cffi:defcfun ("LLVMCountParams" LLVMCountParams) :unsigned-int
  (Fn :pointer))

(cl:export 'LLVMCountParams)

(cffi:defcfun ("LLVMGetParams" LLVMGetParams) :void
  (Fn :pointer)
  (Params :pointer))

(cl:export 'LLVMGetParams)

(cffi:defcfun ("LLVMGetParam" LLVMGetParam) :pointer
  (Fn :pointer)
  (Index :unsigned-int))

(cl:export 'LLVMGetParam)

(cffi:defcfun ("LLVMGetParamParent" LLVMGetParamParent) :pointer
  (Inst :pointer))

(cl:export 'LLVMGetParamParent)

(cffi:defcfun ("LLVMGetFirstParam" LLVMGetFirstParam) :pointer
  (Fn :pointer))

(cl:export 'LLVMGetFirstParam)

(cffi:defcfun ("LLVMGetLastParam" LLVMGetLastParam) :pointer
  (Fn :pointer))

(cl:export 'LLVMGetLastParam)

(cffi:defcfun ("LLVMGetNextParam" LLVMGetNextParam) :pointer
  (Arg :pointer))

(cl:export 'LLVMGetNextParam)

(cffi:defcfun ("LLVMGetPreviousParam" LLVMGetPreviousParam) :pointer
  (Arg :pointer))

(cl:export 'LLVMGetPreviousParam)

(cffi:defcfun ("LLVMAddAttribute" LLVMAddAttribute) :void
  (Arg :pointer)
  (PA LLVMAttribute))

(cl:export 'LLVMAddAttribute)

(cffi:defcfun ("LLVMRemoveAttribute" LLVMRemoveAttribute) :void
  (Arg :pointer)
  (PA LLVMAttribute))

(cl:export 'LLVMRemoveAttribute)

(cffi:defcfun ("LLVMGetAttribute" LLVMGetAttribute) LLVMAttribute
  (Arg :pointer))

(cl:export 'LLVMGetAttribute)

(cffi:defcfun ("LLVMSetParamAlignment" LLVMSetParamAlignment) :void
  (Arg :pointer)
  (align :unsigned-int))

(cl:export 'LLVMSetParamAlignment)

(cffi:defcfun ("LLVMMDStringInContext" LLVMMDStringInContext) :pointer
  (C :pointer)
  (Str :string)
  (SLen :unsigned-int))

(cl:export 'LLVMMDStringInContext)

(cffi:defcfun ("LLVMMDString" LLVMMDString) :pointer
  (Str :string)
  (SLen :unsigned-int))

(cl:export 'LLVMMDString)

(cffi:defcfun ("LLVMMDNodeInContext" LLVMMDNodeInContext) :pointer
  (C :pointer)
  (Vals :pointer)
  (Count :unsigned-int))

(cl:export 'LLVMMDNodeInContext)

(cffi:defcfun ("LLVMMDNode" LLVMMDNode) :pointer
  (Vals :pointer)
  (Count :unsigned-int))

(cl:export 'LLVMMDNode)

(cffi:defcfun ("LLVMGetMDString" LLVMGetMDString) :string
  (V :pointer)
  (Len :pointer))

(cl:export 'LLVMGetMDString)

(cffi:defcfun ("LLVMGetMDNodeNumOperands" LLVMGetMDNodeNumOperands) :unsigned-int
  (V :pointer))

(cl:export 'LLVMGetMDNodeNumOperands)

(cffi:defcfun ("LLVMGetMDNodeOperands" LLVMGetMDNodeOperands) :void
  (V :pointer)
  (Dest :pointer))

(cl:export 'LLVMGetMDNodeOperands)

(cffi:defcfun ("LLVMBasicBlockAsValue" LLVMBasicBlockAsValue) :pointer
  (BB :pointer))

(cl:export 'LLVMBasicBlockAsValue)

(cffi:defcfun ("LLVMValueIsBasicBlock" LLVMValueIsBasicBlock) :int
  (Val :pointer))

(cl:export 'LLVMValueIsBasicBlock)

(cffi:defcfun ("LLVMValueAsBasicBlock" LLVMValueAsBasicBlock) :pointer
  (Val :pointer))

(cl:export 'LLVMValueAsBasicBlock)

(cffi:defcfun ("LLVMGetBasicBlockParent" LLVMGetBasicBlockParent) :pointer
  (BB :pointer))

(cl:export 'LLVMGetBasicBlockParent)

(cffi:defcfun ("LLVMGetBasicBlockTerminator" LLVMGetBasicBlockTerminator) :pointer
  (BB :pointer))

(cl:export 'LLVMGetBasicBlockTerminator)

(cffi:defcfun ("LLVMCountBasicBlocks" LLVMCountBasicBlocks) :unsigned-int
  (Fn :pointer))

(cl:export 'LLVMCountBasicBlocks)

(cffi:defcfun ("LLVMGetBasicBlocks" LLVMGetBasicBlocks) :void
  (Fn :pointer)
  (BasicBlocks :pointer))

(cl:export 'LLVMGetBasicBlocks)

(cffi:defcfun ("LLVMGetFirstBasicBlock" LLVMGetFirstBasicBlock) :pointer
  (Fn :pointer))

(cl:export 'LLVMGetFirstBasicBlock)

(cffi:defcfun ("LLVMGetLastBasicBlock" LLVMGetLastBasicBlock) :pointer
  (Fn :pointer))

(cl:export 'LLVMGetLastBasicBlock)

(cffi:defcfun ("LLVMGetNextBasicBlock" LLVMGetNextBasicBlock) :pointer
  (BB :pointer))

(cl:export 'LLVMGetNextBasicBlock)

(cffi:defcfun ("LLVMGetPreviousBasicBlock" LLVMGetPreviousBasicBlock) :pointer
  (BB :pointer))

(cl:export 'LLVMGetPreviousBasicBlock)

(cffi:defcfun ("LLVMGetEntryBasicBlock" LLVMGetEntryBasicBlock) :pointer
  (Fn :pointer))

(cl:export 'LLVMGetEntryBasicBlock)

(cffi:defcfun ("LLVMAppendBasicBlockInContext" LLVMAppendBasicBlockInContext) :pointer
  (C :pointer)
  (Fn :pointer)
  (Name :string))

(cl:export 'LLVMAppendBasicBlockInContext)

(cffi:defcfun ("LLVMAppendBasicBlock" LLVMAppendBasicBlock) :pointer
  (Fn :pointer)
  (Name :string))

(cl:export 'LLVMAppendBasicBlock)

(cffi:defcfun ("LLVMInsertBasicBlockInContext" LLVMInsertBasicBlockInContext) :pointer
  (C :pointer)
  (BB :pointer)
  (Name :string))

(cl:export 'LLVMInsertBasicBlockInContext)

(cffi:defcfun ("LLVMInsertBasicBlock" LLVMInsertBasicBlock) :pointer
  (InsertBeforeBB :pointer)
  (Name :string))

(cl:export 'LLVMInsertBasicBlock)

(cffi:defcfun ("LLVMDeleteBasicBlock" LLVMDeleteBasicBlock) :void
  (BB :pointer))

(cl:export 'LLVMDeleteBasicBlock)

(cffi:defcfun ("LLVMRemoveBasicBlockFromParent" LLVMRemoveBasicBlockFromParent) :void
  (BB :pointer))

(cl:export 'LLVMRemoveBasicBlockFromParent)

(cffi:defcfun ("LLVMMoveBasicBlockBefore" LLVMMoveBasicBlockBefore) :void
  (BB :pointer)
  (MovePos :pointer))

(cl:export 'LLVMMoveBasicBlockBefore)

(cffi:defcfun ("LLVMMoveBasicBlockAfter" LLVMMoveBasicBlockAfter) :void
  (BB :pointer)
  (MovePos :pointer))

(cl:export 'LLVMMoveBasicBlockAfter)

(cffi:defcfun ("LLVMGetFirstInstruction" LLVMGetFirstInstruction) :pointer
  (BB :pointer))

(cl:export 'LLVMGetFirstInstruction)

(cffi:defcfun ("LLVMGetLastInstruction" LLVMGetLastInstruction) :pointer
  (BB :pointer))

(cl:export 'LLVMGetLastInstruction)

(cffi:defcfun ("LLVMHasMetadata" LLVMHasMetadata) :int
  (Val :pointer))

(cl:export 'LLVMHasMetadata)

(cffi:defcfun ("LLVMGetMetadata" LLVMGetMetadata) :pointer
  (Val :pointer)
  (KindID :unsigned-int))

(cl:export 'LLVMGetMetadata)

(cffi:defcfun ("LLVMSetMetadata" LLVMSetMetadata) :void
  (Val :pointer)
  (KindID :unsigned-int)
  (Node :pointer))

(cl:export 'LLVMSetMetadata)

(cffi:defcfun ("LLVMGetInstructionParent" LLVMGetInstructionParent) :pointer
  (Inst :pointer))

(cl:export 'LLVMGetInstructionParent)

(cffi:defcfun ("LLVMGetNextInstruction" LLVMGetNextInstruction) :pointer
  (Inst :pointer))

(cl:export 'LLVMGetNextInstruction)

(cffi:defcfun ("LLVMGetPreviousInstruction" LLVMGetPreviousInstruction) :pointer
  (Inst :pointer))

(cl:export 'LLVMGetPreviousInstruction)

(cffi:defcfun ("LLVMInstructionEraseFromParent" LLVMInstructionEraseFromParent) :void
  (Inst :pointer))

(cl:export 'LLVMInstructionEraseFromParent)

(cffi:defcfun ("LLVMGetInstructionOpcode" LLVMGetInstructionOpcode) LLVMOpcode
  (Inst :pointer))

(cl:export 'LLVMGetInstructionOpcode)

(cffi:defcfun ("LLVMGetICmpPredicate" LLVMGetICmpPredicate) LLVMIntPredicate
  (Inst :pointer))

(cl:export 'LLVMGetICmpPredicate)

(cffi:defcfun ("LLVMSetInstructionCallConv" LLVMSetInstructionCallConv) :void
  (Instr :pointer)
  (CC :unsigned-int))

(cl:export 'LLVMSetInstructionCallConv)

(cffi:defcfun ("LLVMGetInstructionCallConv" LLVMGetInstructionCallConv) :unsigned-int
  (Instr :pointer))

(cl:export 'LLVMGetInstructionCallConv)

(cffi:defcfun ("LLVMAddInstrAttribute" LLVMAddInstrAttribute) :void
  (Instr :pointer)
  (index :unsigned-int)
  (arg2 LLVMAttribute))

(cl:export 'LLVMAddInstrAttribute)

(cffi:defcfun ("LLVMRemoveInstrAttribute" LLVMRemoveInstrAttribute) :void
  (Instr :pointer)
  (index :unsigned-int)
  (arg2 LLVMAttribute))

(cl:export 'LLVMRemoveInstrAttribute)

(cffi:defcfun ("LLVMSetInstrParamAlignment" LLVMSetInstrParamAlignment) :void
  (Instr :pointer)
  (index :unsigned-int)
  (align :unsigned-int))

(cl:export 'LLVMSetInstrParamAlignment)

(cffi:defcfun ("LLVMIsTailCall" LLVMIsTailCall) :int
  (CallInst :pointer))

(cl:export 'LLVMIsTailCall)

(cffi:defcfun ("LLVMSetTailCall" LLVMSetTailCall) :void
  (CallInst :pointer)
  (IsTailCall :int))

(cl:export 'LLVMSetTailCall)

(cffi:defcfun ("LLVMGetSwitchDefaultDest" LLVMGetSwitchDefaultDest) :pointer
  (SwitchInstr :pointer))

(cl:export 'LLVMGetSwitchDefaultDest)

(cffi:defcfun ("LLVMAddIncoming" LLVMAddIncoming) :void
  (PhiNode :pointer)
  (IncomingValues :pointer)
  (IncomingBlocks :pointer)
  (Count :unsigned-int))

(cl:export 'LLVMAddIncoming)

(cffi:defcfun ("LLVMCountIncoming" LLVMCountIncoming) :unsigned-int
  (PhiNode :pointer))

(cl:export 'LLVMCountIncoming)

(cffi:defcfun ("LLVMGetIncomingValue" LLVMGetIncomingValue) :pointer
  (PhiNode :pointer)
  (Index :unsigned-int))

(cl:export 'LLVMGetIncomingValue)

(cffi:defcfun ("LLVMGetIncomingBlock" LLVMGetIncomingBlock) :pointer
  (PhiNode :pointer)
  (Index :unsigned-int))

(cl:export 'LLVMGetIncomingBlock)

(cffi:defcfun ("LLVMCreateBuilderInContext" LLVMCreateBuilderInContext) :pointer
  (C :pointer))

(cl:export 'LLVMCreateBuilderInContext)

(cffi:defcfun ("LLVMCreateBuilder" LLVMCreateBuilder) :pointer)

(cl:export 'LLVMCreateBuilder)

(cffi:defcfun ("LLVMPositionBuilder" LLVMPositionBuilder) :void
  (Builder :pointer)
  (Block :pointer)
  (Instr :pointer))

(cl:export 'LLVMPositionBuilder)

(cffi:defcfun ("LLVMPositionBuilderBefore" LLVMPositionBuilderBefore) :void
  (Builder :pointer)
  (Instr :pointer))

(cl:export 'LLVMPositionBuilderBefore)

(cffi:defcfun ("LLVMPositionBuilderAtEnd" LLVMPositionBuilderAtEnd) :void
  (Builder :pointer)
  (Block :pointer))

(cl:export 'LLVMPositionBuilderAtEnd)

(cffi:defcfun ("LLVMGetInsertBlock" LLVMGetInsertBlock) :pointer
  (Builder :pointer))

(cl:export 'LLVMGetInsertBlock)

(cffi:defcfun ("LLVMClearInsertionPosition" LLVMClearInsertionPosition) :void
  (Builder :pointer))

(cl:export 'LLVMClearInsertionPosition)

(cffi:defcfun ("LLVMInsertIntoBuilder" LLVMInsertIntoBuilder) :void
  (Builder :pointer)
  (Instr :pointer))

(cl:export 'LLVMInsertIntoBuilder)

(cffi:defcfun ("LLVMInsertIntoBuilderWithName" LLVMInsertIntoBuilderWithName) :void
  (Builder :pointer)
  (Instr :pointer)
  (Name :string))

(cl:export 'LLVMInsertIntoBuilderWithName)

(cffi:defcfun ("LLVMDisposeBuilder" LLVMDisposeBuilder) :void
  (Builder :pointer))

(cl:export 'LLVMDisposeBuilder)

(cffi:defcfun ("LLVMSetCurrentDebugLocation" LLVMSetCurrentDebugLocation) :void
  (Builder :pointer)
  (L :pointer))

(cl:export 'LLVMSetCurrentDebugLocation)

(cffi:defcfun ("LLVMGetCurrentDebugLocation" LLVMGetCurrentDebugLocation) :pointer
  (Builder :pointer))

(cl:export 'LLVMGetCurrentDebugLocation)

(cffi:defcfun ("LLVMSetInstDebugLocation" LLVMSetInstDebugLocation) :void
  (Builder :pointer)
  (Inst :pointer))

(cl:export 'LLVMSetInstDebugLocation)

(cffi:defcfun ("LLVMBuildRetVoid" LLVMBuildRetVoid) :pointer
  (arg0 :pointer))

(cl:export 'LLVMBuildRetVoid)

(cffi:defcfun ("LLVMBuildRet" LLVMBuildRet) :pointer
  (arg0 :pointer)
  (V :pointer))

(cl:export 'LLVMBuildRet)

(cffi:defcfun ("LLVMBuildAggregateRet" LLVMBuildAggregateRet) :pointer
  (arg0 :pointer)
  (RetVals :pointer)
  (N :unsigned-int))

(cl:export 'LLVMBuildAggregateRet)

(cffi:defcfun ("LLVMBuildBr" LLVMBuildBr) :pointer
  (arg0 :pointer)
  (Dest :pointer))

(cl:export 'LLVMBuildBr)

(cffi:defcfun ("LLVMBuildCondBr" LLVMBuildCondBr) :pointer
  (arg0 :pointer)
  (If :pointer)
  (Then :pointer)
  (Else :pointer))

(cl:export 'LLVMBuildCondBr)

(cffi:defcfun ("LLVMBuildSwitch" LLVMBuildSwitch) :pointer
  (arg0 :pointer)
  (V :pointer)
  (Else :pointer)
  (NumCases :unsigned-int))

(cl:export 'LLVMBuildSwitch)

(cffi:defcfun ("LLVMBuildIndirectBr" LLVMBuildIndirectBr) :pointer
  (B :pointer)
  (Addr :pointer)
  (NumDests :unsigned-int))

(cl:export 'LLVMBuildIndirectBr)

(cffi:defcfun ("LLVMBuildInvoke" LLVMBuildInvoke) :pointer
  (arg0 :pointer)
  (Fn :pointer)
  (Args :pointer)
  (NumArgs :unsigned-int)
  (Then :pointer)
  (Catch :pointer)
  (Name :string))

(cl:export 'LLVMBuildInvoke)

(cffi:defcfun ("LLVMBuildLandingPad" LLVMBuildLandingPad) :pointer
  (B :pointer)
  (Ty :pointer)
  (PersFn :pointer)
  (NumClauses :unsigned-int)
  (Name :string))

(cl:export 'LLVMBuildLandingPad)

(cffi:defcfun ("LLVMBuildResume" LLVMBuildResume) :pointer
  (B :pointer)
  (Exn :pointer))

(cl:export 'LLVMBuildResume)

(cffi:defcfun ("LLVMBuildUnreachable" LLVMBuildUnreachable) :pointer
  (arg0 :pointer))

(cl:export 'LLVMBuildUnreachable)

(cffi:defcfun ("LLVMAddCase" LLVMAddCase) :void
  (Switch :pointer)
  (OnVal :pointer)
  (Dest :pointer))

(cl:export 'LLVMAddCase)

(cffi:defcfun ("LLVMAddDestination" LLVMAddDestination) :void
  (IndirectBr :pointer)
  (Dest :pointer))

(cl:export 'LLVMAddDestination)

(cffi:defcfun ("LLVMAddClause" LLVMAddClause) :void
  (LandingPad :pointer)
  (ClauseVal :pointer))

(cl:export 'LLVMAddClause)

(cffi:defcfun ("LLVMSetCleanup" LLVMSetCleanup) :void
  (LandingPad :pointer)
  (Val :int))

(cl:export 'LLVMSetCleanup)

(cffi:defcfun ("LLVMBuildAdd" LLVMBuildAdd) :pointer
  (arg0 :pointer)
  (LHS :pointer)
  (RHS :pointer)
  (Name :string))

(cl:export 'LLVMBuildAdd)

(cffi:defcfun ("LLVMBuildNSWAdd" LLVMBuildNSWAdd) :pointer
  (arg0 :pointer)
  (LHS :pointer)
  (RHS :pointer)
  (Name :string))

(cl:export 'LLVMBuildNSWAdd)

(cffi:defcfun ("LLVMBuildNUWAdd" LLVMBuildNUWAdd) :pointer
  (arg0 :pointer)
  (LHS :pointer)
  (RHS :pointer)
  (Name :string))

(cl:export 'LLVMBuildNUWAdd)

(cffi:defcfun ("LLVMBuildFAdd" LLVMBuildFAdd) :pointer
  (arg0 :pointer)
  (LHS :pointer)
  (RHS :pointer)
  (Name :string))

(cl:export 'LLVMBuildFAdd)

(cffi:defcfun ("LLVMBuildSub" LLVMBuildSub) :pointer
  (arg0 :pointer)
  (LHS :pointer)
  (RHS :pointer)
  (Name :string))

(cl:export 'LLVMBuildSub)

(cffi:defcfun ("LLVMBuildNSWSub" LLVMBuildNSWSub) :pointer
  (arg0 :pointer)
  (LHS :pointer)
  (RHS :pointer)
  (Name :string))

(cl:export 'LLVMBuildNSWSub)

(cffi:defcfun ("LLVMBuildNUWSub" LLVMBuildNUWSub) :pointer
  (arg0 :pointer)
  (LHS :pointer)
  (RHS :pointer)
  (Name :string))

(cl:export 'LLVMBuildNUWSub)

(cffi:defcfun ("LLVMBuildFSub" LLVMBuildFSub) :pointer
  (arg0 :pointer)
  (LHS :pointer)
  (RHS :pointer)
  (Name :string))

(cl:export 'LLVMBuildFSub)

(cffi:defcfun ("LLVMBuildMul" LLVMBuildMul) :pointer
  (arg0 :pointer)
  (LHS :pointer)
  (RHS :pointer)
  (Name :string))

(cl:export 'LLVMBuildMul)

(cffi:defcfun ("LLVMBuildNSWMul" LLVMBuildNSWMul) :pointer
  (arg0 :pointer)
  (LHS :pointer)
  (RHS :pointer)
  (Name :string))

(cl:export 'LLVMBuildNSWMul)

(cffi:defcfun ("LLVMBuildNUWMul" LLVMBuildNUWMul) :pointer
  (arg0 :pointer)
  (LHS :pointer)
  (RHS :pointer)
  (Name :string))

(cl:export 'LLVMBuildNUWMul)

(cffi:defcfun ("LLVMBuildFMul" LLVMBuildFMul) :pointer
  (arg0 :pointer)
  (LHS :pointer)
  (RHS :pointer)
  (Name :string))

(cl:export 'LLVMBuildFMul)

(cffi:defcfun ("LLVMBuildUDiv" LLVMBuildUDiv) :pointer
  (arg0 :pointer)
  (LHS :pointer)
  (RHS :pointer)
  (Name :string))

(cl:export 'LLVMBuildUDiv)

(cffi:defcfun ("LLVMBuildSDiv" LLVMBuildSDiv) :pointer
  (arg0 :pointer)
  (LHS :pointer)
  (RHS :pointer)
  (Name :string))

(cl:export 'LLVMBuildSDiv)

(cffi:defcfun ("LLVMBuildExactSDiv" LLVMBuildExactSDiv) :pointer
  (arg0 :pointer)
  (LHS :pointer)
  (RHS :pointer)
  (Name :string))

(cl:export 'LLVMBuildExactSDiv)

(cffi:defcfun ("LLVMBuildFDiv" LLVMBuildFDiv) :pointer
  (arg0 :pointer)
  (LHS :pointer)
  (RHS :pointer)
  (Name :string))

(cl:export 'LLVMBuildFDiv)

(cffi:defcfun ("LLVMBuildURem" LLVMBuildURem) :pointer
  (arg0 :pointer)
  (LHS :pointer)
  (RHS :pointer)
  (Name :string))

(cl:export 'LLVMBuildURem)

(cffi:defcfun ("LLVMBuildSRem" LLVMBuildSRem) :pointer
  (arg0 :pointer)
  (LHS :pointer)
  (RHS :pointer)
  (Name :string))

(cl:export 'LLVMBuildSRem)

(cffi:defcfun ("LLVMBuildFRem" LLVMBuildFRem) :pointer
  (arg0 :pointer)
  (LHS :pointer)
  (RHS :pointer)
  (Name :string))

(cl:export 'LLVMBuildFRem)

(cffi:defcfun ("LLVMBuildShl" LLVMBuildShl) :pointer
  (arg0 :pointer)
  (LHS :pointer)
  (RHS :pointer)
  (Name :string))

(cl:export 'LLVMBuildShl)

(cffi:defcfun ("LLVMBuildLShr" LLVMBuildLShr) :pointer
  (arg0 :pointer)
  (LHS :pointer)
  (RHS :pointer)
  (Name :string))

(cl:export 'LLVMBuildLShr)

(cffi:defcfun ("LLVMBuildAShr" LLVMBuildAShr) :pointer
  (arg0 :pointer)
  (LHS :pointer)
  (RHS :pointer)
  (Name :string))

(cl:export 'LLVMBuildAShr)

(cffi:defcfun ("LLVMBuildAnd" LLVMBuildAnd) :pointer
  (arg0 :pointer)
  (LHS :pointer)
  (RHS :pointer)
  (Name :string))

(cl:export 'LLVMBuildAnd)

(cffi:defcfun ("LLVMBuildOr" LLVMBuildOr) :pointer
  (arg0 :pointer)
  (LHS :pointer)
  (RHS :pointer)
  (Name :string))

(cl:export 'LLVMBuildOr)

(cffi:defcfun ("LLVMBuildXor" LLVMBuildXor) :pointer
  (arg0 :pointer)
  (LHS :pointer)
  (RHS :pointer)
  (Name :string))

(cl:export 'LLVMBuildXor)

(cffi:defcfun ("LLVMBuildBinOp" LLVMBuildBinOp) :pointer
  (B :pointer)
  (Op LLVMOpcode)
  (LHS :pointer)
  (RHS :pointer)
  (Name :string))

(cl:export 'LLVMBuildBinOp)

(cffi:defcfun ("LLVMBuildNeg" LLVMBuildNeg) :pointer
  (arg0 :pointer)
  (V :pointer)
  (Name :string))

(cl:export 'LLVMBuildNeg)

(cffi:defcfun ("LLVMBuildNSWNeg" LLVMBuildNSWNeg) :pointer
  (B :pointer)
  (V :pointer)
  (Name :string))

(cl:export 'LLVMBuildNSWNeg)

(cffi:defcfun ("LLVMBuildNUWNeg" LLVMBuildNUWNeg) :pointer
  (B :pointer)
  (V :pointer)
  (Name :string))

(cl:export 'LLVMBuildNUWNeg)

(cffi:defcfun ("LLVMBuildFNeg" LLVMBuildFNeg) :pointer
  (arg0 :pointer)
  (V :pointer)
  (Name :string))

(cl:export 'LLVMBuildFNeg)

(cffi:defcfun ("LLVMBuildNot" LLVMBuildNot) :pointer
  (arg0 :pointer)
  (V :pointer)
  (Name :string))

(cl:export 'LLVMBuildNot)

(cffi:defcfun ("LLVMBuildMalloc" LLVMBuildMalloc) :pointer
  (arg0 :pointer)
  (Ty :pointer)
  (Name :string))

(cl:export 'LLVMBuildMalloc)

(cffi:defcfun ("LLVMBuildArrayMalloc" LLVMBuildArrayMalloc) :pointer
  (arg0 :pointer)
  (Ty :pointer)
  (Val :pointer)
  (Name :string))

(cl:export 'LLVMBuildArrayMalloc)

(cffi:defcfun ("LLVMBuildAlloca" LLVMBuildAlloca) :pointer
  (arg0 :pointer)
  (Ty :pointer)
  (Name :string))

(cl:export 'LLVMBuildAlloca)

(cffi:defcfun ("LLVMBuildArrayAlloca" LLVMBuildArrayAlloca) :pointer
  (arg0 :pointer)
  (Ty :pointer)
  (Val :pointer)
  (Name :string))

(cl:export 'LLVMBuildArrayAlloca)

(cffi:defcfun ("LLVMBuildFree" LLVMBuildFree) :pointer
  (arg0 :pointer)
  (PointerVal :pointer))

(cl:export 'LLVMBuildFree)

(cffi:defcfun ("LLVMBuildLoad" LLVMBuildLoad) :pointer
  (arg0 :pointer)
  (PointerVal :pointer)
  (Name :string))

(cl:export 'LLVMBuildLoad)

(cffi:defcfun ("LLVMBuildStore" LLVMBuildStore) :pointer
  (arg0 :pointer)
  (Val :pointer)
  (Ptr :pointer))

(cl:export 'LLVMBuildStore)

(cffi:defcfun ("LLVMBuildGEP" LLVMBuildGEP) :pointer
  (B :pointer)
  (Pointer :pointer)
  (Indices :pointer)
  (NumIndices :unsigned-int)
  (Name :string))

(cl:export 'LLVMBuildGEP)

(cffi:defcfun ("LLVMBuildInBoundsGEP" LLVMBuildInBoundsGEP) :pointer
  (B :pointer)
  (Pointer :pointer)
  (Indices :pointer)
  (NumIndices :unsigned-int)
  (Name :string))

(cl:export 'LLVMBuildInBoundsGEP)

(cffi:defcfun ("LLVMBuildStructGEP" LLVMBuildStructGEP) :pointer
  (B :pointer)
  (Pointer :pointer)
  (Idx :unsigned-int)
  (Name :string))

(cl:export 'LLVMBuildStructGEP)

(cffi:defcfun ("LLVMBuildGlobalString" LLVMBuildGlobalString) :pointer
  (B :pointer)
  (Str :string)
  (Name :string))

(cl:export 'LLVMBuildGlobalString)

(cffi:defcfun ("LLVMBuildGlobalStringPtr" LLVMBuildGlobalStringPtr) :pointer
  (B :pointer)
  (Str :string)
  (Name :string))

(cl:export 'LLVMBuildGlobalStringPtr)

(cffi:defcfun ("LLVMGetVolatile" LLVMGetVolatile) :int
  (MemoryAccessInst :pointer))

(cl:export 'LLVMGetVolatile)

(cffi:defcfun ("LLVMSetVolatile" LLVMSetVolatile) :void
  (MemoryAccessInst :pointer)
  (IsVolatile :int))

(cl:export 'LLVMSetVolatile)

(cffi:defcfun ("LLVMBuildTrunc" LLVMBuildTrunc) :pointer
  (arg0 :pointer)
  (Val :pointer)
  (DestTy :pointer)
  (Name :string))

(cl:export 'LLVMBuildTrunc)

(cffi:defcfun ("LLVMBuildZExt" LLVMBuildZExt) :pointer
  (arg0 :pointer)
  (Val :pointer)
  (DestTy :pointer)
  (Name :string))

(cl:export 'LLVMBuildZExt)

(cffi:defcfun ("LLVMBuildSExt" LLVMBuildSExt) :pointer
  (arg0 :pointer)
  (Val :pointer)
  (DestTy :pointer)
  (Name :string))

(cl:export 'LLVMBuildSExt)

(cffi:defcfun ("LLVMBuildFPToUI" LLVMBuildFPToUI) :pointer
  (arg0 :pointer)
  (Val :pointer)
  (DestTy :pointer)
  (Name :string))

(cl:export 'LLVMBuildFPToUI)

(cffi:defcfun ("LLVMBuildFPToSI" LLVMBuildFPToSI) :pointer
  (arg0 :pointer)
  (Val :pointer)
  (DestTy :pointer)
  (Name :string))

(cl:export 'LLVMBuildFPToSI)

(cffi:defcfun ("LLVMBuildUIToFP" LLVMBuildUIToFP) :pointer
  (arg0 :pointer)
  (Val :pointer)
  (DestTy :pointer)
  (Name :string))

(cl:export 'LLVMBuildUIToFP)

(cffi:defcfun ("LLVMBuildSIToFP" LLVMBuildSIToFP) :pointer
  (arg0 :pointer)
  (Val :pointer)
  (DestTy :pointer)
  (Name :string))

(cl:export 'LLVMBuildSIToFP)

(cffi:defcfun ("LLVMBuildFPTrunc" LLVMBuildFPTrunc) :pointer
  (arg0 :pointer)
  (Val :pointer)
  (DestTy :pointer)
  (Name :string))

(cl:export 'LLVMBuildFPTrunc)

(cffi:defcfun ("LLVMBuildFPExt" LLVMBuildFPExt) :pointer
  (arg0 :pointer)
  (Val :pointer)
  (DestTy :pointer)
  (Name :string))

(cl:export 'LLVMBuildFPExt)

(cffi:defcfun ("LLVMBuildPtrToInt" LLVMBuildPtrToInt) :pointer
  (arg0 :pointer)
  (Val :pointer)
  (DestTy :pointer)
  (Name :string))

(cl:export 'LLVMBuildPtrToInt)

(cffi:defcfun ("LLVMBuildIntToPtr" LLVMBuildIntToPtr) :pointer
  (arg0 :pointer)
  (Val :pointer)
  (DestTy :pointer)
  (Name :string))

(cl:export 'LLVMBuildIntToPtr)

(cffi:defcfun ("LLVMBuildBitCast" LLVMBuildBitCast) :pointer
  (arg0 :pointer)
  (Val :pointer)
  (DestTy :pointer)
  (Name :string))

(cl:export 'LLVMBuildBitCast)

(cffi:defcfun ("LLVMBuildAddrSpaceCast" LLVMBuildAddrSpaceCast) :pointer
  (arg0 :pointer)
  (Val :pointer)
  (DestTy :pointer)
  (Name :string))

(cl:export 'LLVMBuildAddrSpaceCast)

(cffi:defcfun ("LLVMBuildZExtOrBitCast" LLVMBuildZExtOrBitCast) :pointer
  (arg0 :pointer)
  (Val :pointer)
  (DestTy :pointer)
  (Name :string))

(cl:export 'LLVMBuildZExtOrBitCast)

(cffi:defcfun ("LLVMBuildSExtOrBitCast" LLVMBuildSExtOrBitCast) :pointer
  (arg0 :pointer)
  (Val :pointer)
  (DestTy :pointer)
  (Name :string))

(cl:export 'LLVMBuildSExtOrBitCast)

(cffi:defcfun ("LLVMBuildTruncOrBitCast" LLVMBuildTruncOrBitCast) :pointer
  (arg0 :pointer)
  (Val :pointer)
  (DestTy :pointer)
  (Name :string))

(cl:export 'LLVMBuildTruncOrBitCast)

(cffi:defcfun ("LLVMBuildCast" LLVMBuildCast) :pointer
  (B :pointer)
  (Op LLVMOpcode)
  (Val :pointer)
  (DestTy :pointer)
  (Name :string))

(cl:export 'LLVMBuildCast)

(cffi:defcfun ("LLVMBuildPointerCast" LLVMBuildPointerCast) :pointer
  (arg0 :pointer)
  (Val :pointer)
  (DestTy :pointer)
  (Name :string))

(cl:export 'LLVMBuildPointerCast)

(cffi:defcfun ("LLVMBuildIntCast" LLVMBuildIntCast) :pointer
  (arg0 :pointer)
  (Val :pointer)
  (DestTy :pointer)
  (Name :string))

(cl:export 'LLVMBuildIntCast)

(cffi:defcfun ("LLVMBuildFPCast" LLVMBuildFPCast) :pointer
  (arg0 :pointer)
  (Val :pointer)
  (DestTy :pointer)
  (Name :string))

(cl:export 'LLVMBuildFPCast)

(cffi:defcfun ("LLVMBuildICmp" LLVMBuildICmp) :pointer
  (arg0 :pointer)
  (Op LLVMIntPredicate)
  (LHS :pointer)
  (RHS :pointer)
  (Name :string))

(cl:export 'LLVMBuildICmp)

(cffi:defcfun ("LLVMBuildFCmp" LLVMBuildFCmp) :pointer
  (arg0 :pointer)
  (Op LLVMRealPredicate)
  (LHS :pointer)
  (RHS :pointer)
  (Name :string))

(cl:export 'LLVMBuildFCmp)

(cffi:defcfun ("LLVMBuildPhi" LLVMBuildPhi) :pointer
  (arg0 :pointer)
  (Ty :pointer)
  (Name :string))

(cl:export 'LLVMBuildPhi)

(cffi:defcfun ("LLVMBuildCall" LLVMBuildCall) :pointer
  (arg0 :pointer)
  (Fn :pointer)
  (Args :pointer)
  (NumArgs :unsigned-int)
  (Name :string))

(cl:export 'LLVMBuildCall)

(cffi:defcfun ("LLVMBuildSelect" LLVMBuildSelect) :pointer
  (arg0 :pointer)
  (If :pointer)
  (Then :pointer)
  (Else :pointer)
  (Name :string))

(cl:export 'LLVMBuildSelect)

(cffi:defcfun ("LLVMBuildVAArg" LLVMBuildVAArg) :pointer
  (arg0 :pointer)
  (List :pointer)
  (Ty :pointer)
  (Name :string))

(cl:export 'LLVMBuildVAArg)

(cffi:defcfun ("LLVMBuildExtractElement" LLVMBuildExtractElement) :pointer
  (arg0 :pointer)
  (VecVal :pointer)
  (Index :pointer)
  (Name :string))

(cl:export 'LLVMBuildExtractElement)

(cffi:defcfun ("LLVMBuildInsertElement" LLVMBuildInsertElement) :pointer
  (arg0 :pointer)
  (VecVal :pointer)
  (EltVal :pointer)
  (Index :pointer)
  (Name :string))

(cl:export 'LLVMBuildInsertElement)

(cffi:defcfun ("LLVMBuildShuffleVector" LLVMBuildShuffleVector) :pointer
  (arg0 :pointer)
  (V1 :pointer)
  (V2 :pointer)
  (Mask :pointer)
  (Name :string))

(cl:export 'LLVMBuildShuffleVector)

(cffi:defcfun ("LLVMBuildExtractValue" LLVMBuildExtractValue) :pointer
  (arg0 :pointer)
  (AggVal :pointer)
  (Index :unsigned-int)
  (Name :string))

(cl:export 'LLVMBuildExtractValue)

(cffi:defcfun ("LLVMBuildInsertValue" LLVMBuildInsertValue) :pointer
  (arg0 :pointer)
  (AggVal :pointer)
  (EltVal :pointer)
  (Index :unsigned-int)
  (Name :string))

(cl:export 'LLVMBuildInsertValue)

(cffi:defcfun ("LLVMBuildIsNull" LLVMBuildIsNull) :pointer
  (arg0 :pointer)
  (Val :pointer)
  (Name :string))

(cl:export 'LLVMBuildIsNull)

(cffi:defcfun ("LLVMBuildIsNotNull" LLVMBuildIsNotNull) :pointer
  (arg0 :pointer)
  (Val :pointer)
  (Name :string))

(cl:export 'LLVMBuildIsNotNull)

(cffi:defcfun ("LLVMBuildPtrDiff" LLVMBuildPtrDiff) :pointer
  (arg0 :pointer)
  (LHS :pointer)
  (RHS :pointer)
  (Name :string))

(cl:export 'LLVMBuildPtrDiff)

(cffi:defcfun ("LLVMBuildAtomicRMW" LLVMBuildAtomicRMW) :pointer
  (B :pointer)
  (op LLVMAtomicRMWBinOp)
  (PTR :pointer)
  (Val :pointer)
  (ordering LLVMAtomicOrdering)
  (singleThread :int))

(cl:export 'LLVMBuildAtomicRMW)

(cffi:defcfun ("LLVMCreateModuleProviderForExistingModule" LLVMCreateModuleProviderForExistingModule) :pointer
  (M :pointer))

(cl:export 'LLVMCreateModuleProviderForExistingModule)

(cffi:defcfun ("LLVMDisposeModuleProvider" LLVMDisposeModuleProvider) :void
  (M :pointer))

(cl:export 'LLVMDisposeModuleProvider)

(cffi:defcfun ("LLVMCreateMemoryBufferWithContentsOfFile" LLVMCreateMemoryBufferWithContentsOfFile) :int
  (Path :string)
  (OutMemBuf :pointer)
  (OutMessage :pointer))

(cl:export 'LLVMCreateMemoryBufferWithContentsOfFile)

(cffi:defcfun ("LLVMCreateMemoryBufferWithSTDIN" LLVMCreateMemoryBufferWithSTDIN) :int
  (OutMemBuf :pointer)
  (OutMessage :pointer))

(cl:export 'LLVMCreateMemoryBufferWithSTDIN)

(cffi:defcfun ("LLVMCreateMemoryBufferWithMemoryRange" LLVMCreateMemoryBufferWithMemoryRange) :pointer
  (InputData :string)
  (InputDataLength :pointer)
  (BufferName :string)
  (RequiresNullTerminator :int))

(cl:export 'LLVMCreateMemoryBufferWithMemoryRange)

(cffi:defcfun ("LLVMCreateMemoryBufferWithMemoryRangeCopy" LLVMCreateMemoryBufferWithMemoryRangeCopy) :pointer
  (InputData :string)
  (InputDataLength :pointer)
  (BufferName :string))

(cl:export 'LLVMCreateMemoryBufferWithMemoryRangeCopy)

(cffi:defcfun ("LLVMGetBufferStart" LLVMGetBufferStart) :string
  (MemBuf :pointer))

(cl:export 'LLVMGetBufferStart)

(cffi:defcfun ("LLVMGetBufferSize" LLVMGetBufferSize) :pointer
  (MemBuf :pointer))

(cl:export 'LLVMGetBufferSize)

(cffi:defcfun ("LLVMDisposeMemoryBuffer" LLVMDisposeMemoryBuffer) :void
  (MemBuf :pointer))

(cl:export 'LLVMDisposeMemoryBuffer)

(cffi:defcfun ("LLVMGetGlobalPassRegistry" LLVMGetGlobalPassRegistry) :pointer)

(cl:export 'LLVMGetGlobalPassRegistry)

(cffi:defcfun ("LLVMCreatePassManager" LLVMCreatePassManager) :pointer)

(cl:export 'LLVMCreatePassManager)

(cffi:defcfun ("LLVMCreateFunctionPassManagerForModule" LLVMCreateFunctionPassManagerForModule) :pointer
  (M :pointer))

(cl:export 'LLVMCreateFunctionPassManagerForModule)

(cffi:defcfun ("LLVMCreateFunctionPassManager" LLVMCreateFunctionPassManager) :pointer
  (MP :pointer))

(cl:export 'LLVMCreateFunctionPassManager)

(cffi:defcfun ("LLVMRunPassManager" LLVMRunPassManager) :int
  (PM :pointer)
  (M :pointer))

(cl:export 'LLVMRunPassManager)

(cffi:defcfun ("LLVMInitializeFunctionPassManager" LLVMInitializeFunctionPassManager) :int
  (FPM :pointer))

(cl:export 'LLVMInitializeFunctionPassManager)

(cffi:defcfun ("LLVMRunFunctionPassManager" LLVMRunFunctionPassManager) :int
  (FPM :pointer)
  (F :pointer))

(cl:export 'LLVMRunFunctionPassManager)

(cffi:defcfun ("LLVMFinalizeFunctionPassManager" LLVMFinalizeFunctionPassManager) :int
  (FPM :pointer))

(cl:export 'LLVMFinalizeFunctionPassManager)

(cffi:defcfun ("LLVMDisposePassManager" LLVMDisposePassManager) :void
  (PM :pointer))

(cl:export 'LLVMDisposePassManager)

(cffi:defcfun ("LLVMStartMultithreaded" LLVMStartMultithreaded) :int)

(cl:export 'LLVMStartMultithreaded)

(cffi:defcfun ("LLVMStopMultithreaded" LLVMStopMultithreaded) :void)

(cl:export 'LLVMStopMultithreaded)

(cffi:defcfun ("LLVMIsMultithreaded" LLVMIsMultithreaded) :int)

(cl:export 'LLVMIsMultithreaded)


