(in-package :owlisp/register)

(export '(make-machine))



(defun make-machine ()
  (let ((gp-registers (make-keyvalue-map))
	(pc '())
	(callstack '())
	(csp '())
	(code '()))
    (labels ((get-register (reg)
	       (lookup-in-keyvalue-map gp-registers
				       reg))
	     ((setf get-register) (val reg)
	       (update-in-keyvalue-map gp-registers
				       reg
				       val))
	     (get-code ()
	       code)
	     ((setf get-code) (val)
	       (setf code val))
	     (reset ()
	       (setf pc code))
	     (step-instruction ()
	       (let* ((instr (first pc))
		      (op (first instr)))
		 (case (intern (symbol-name op) 'keyword)
		   (:mov (let ((reg-src (second instr))
			       (reg-dest (third instr)))
			   (setf (get-register reg-dest)
				 (get-register reg-src))))
		   (t (error "unknown operation")))
		 (setf pc (rest pc)))))
      (lambda (action)
	(case action
	  (:get-register #'get-register)
	  (:set-register #'(lambda (reg val)
			     (setf (get-register reg) val)))
	  (:get-code #'get-code)
	  (:set-code #'(lambda (new-code)
			 (setf (get-code) new-code)))
	  (:reset #'reset)
	  (:step-instruction #'step-instruction)
	  (:print #'(lambda ()
		      (format t "pc:~a~%code:~a~%" pc code)
		      (maphash #'(lambda (k v)
				   (format t "~a:~a~%" k v))
			       gp-registers))))))))
