(in-package :owlisp/llvm)



(defvar *value_container_t*)
(defvar *value_t*)
(defvar *value_p*)
(defvar *frame_t*)
(defvar *frame_p*)
(defvar *arecord_t*)
(defvar *arecord_p*)
(defvar *fn-type*)
(defvar *main-fn-type*)

(defvar *new_value*)
(defvar *get_binding*)
(defvar *new_frame*)
(defvar *set_binding*)
(defvar *init_global_frame*)
(defvar *get_global_frame*)
(defvar *new_arecord*)
(defvar *set_static_link*)
(defvar *get_static_link*)
(defvar *set_dynamic_link*)
(defvar *get_dynamic_link*)
(defvar *set_local_variables*)
(defvar *get_local_variables*)
(defvar *extend_global_frame*)
(defvar *shrink_global_frame*)
(defvar *is_value_true*)
